Issue/iso3 version bump
inmanta/inmanta-core pull request #2738
Opened 2021-02-25 15:53 UTC by sanderr

part of inmanta/irt#520

2021-02-25 16:24 UTC, wouterdb approved these changes

2021-02-26 07:38 UTC, arnaudsjs requested changes
Why not bump version in `tests_common/setup.py`?

2021-02-26 08:20 UTC, sanderr commented
I missed that. I'm not sure it needs to be bumped in general: I seem to recall we discussed this on slack and decided we'd decouple it for iso3, only bumping and releasing it when there have actually been changes. That said, in this case we made some changes to the version constraints so it definitely needs to be bumped. We can save the rest of the discussion for when we're working on the release tool.

2021-02-26 12:45 UTC, arnaudsjs approved these changes

2021-02-26 13:06 UTC, merged