Fix TCP port range and string interpolation typos
inmanta/inmanta-core pull request #2759
Opened 2021-03-04 10:42 UTC by Pouriya-Inmanta

# Description

* Fixed TCP port range and string interpolation typos in language.rst file *

* TCP port range changed from 0-65565 to 0-65535
* Changed "include" to "included" under string interpolation section

2021-03-04 11:00 UTC, wouterdb requested changes

2021-03-04 11:00 UTC, wouterdb commented on changelogs/unreleased/0000000001-typo_fix.yml
> +  known-issue: "4 byte unicode character are not supported"
all the sections other then bug fix should be removed (i.e. you have nothing to add to these sections)

2021-03-04 11:14 UTC, sanderr requested changes

2021-03-04 11:14 UTC, sanderr commented on changelogs/unreleased/0000000001-typo_fix.yml
> +issue-nr: N/A
This will cause a type error when parsing the file. Currently you should just leave the field out if there's no related issue.
```suggestion
```

2021-03-04 11:36 UTC, sanderr commented
Also, perhaps `YYYYMMDD-description` makes more sense than `00000000001-description` when there's no related issue. We haven't discussed this before. @wouterdb what do you think?

2021-03-04 12:17 UTC, wouterdb commented
> Also, perhaps `YYYYMMDD-description` makes more sense than `00000000001-description` when there's no related issue. We haven't discussed this before. @wouterdb what do you think?

Good question. I don't know. We can do just 'description' or '0-description' 

I would like something that produces a somewhat uniform sorting, be the current format doesn't say how long the number should be either. 

Perhaps a question for slack?

2021-03-04 12:18 UTC, wouterdb requested changes

2021-03-04 12:18 UTC, wouterdb commented on changelogs/unreleased/0000000001-typo_fix.yml
> +  other-note: |
the other-note I would remove as well, this is not sufficiently important to put in the changelog.

2021-03-04 12:23 UTC, Pouriya-Inmanta reviewed
Done

2021-03-04 14:59 UTC, sanderr approved these changes

2021-03-04 15:27 UTC, wouterdb approved these changes

2021-03-05 12:10 UTC, inmantaci commented
Processing this pull request

2021-03-05 12:10 UTC, inmantaci commented
Merged into branches master in cbfe09d0feacd1f7f617d7723bcd04240aaf9ae5

2021-03-05 12:10 UTC, closed without merging

2021-03-05 12:10 UTC, inmantaci commented
Processing #2764.

2021-03-05 12:10 UTC, inmantaci commented
Processing #2763.