Issue/inmanta lsm 408 diagnosis endpoint
inmanta/inmanta-core pull request #2848
Opened 2021-04-09 12:57 UTC by sanderr

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2021-04-09 13:20 UTC, arnaudsjs requested changes

2021-04-09 13:20 UTC, arnaudsjs commented on docs/reference/api.rst
> + changes added to commit (use "git add" and/or "git commit -a")
?

2021-04-09 13:26 UTC, sanderr commented on docs/reference/api.rst
> + changes added to commit (use "git add" and/or "git commit -a")
Something weird happened here

2021-04-12 07:08 UTC, wouterdb approved these changes

2021-04-12 09:33 UTC, arnaudsjs approved these changes

2021-04-12 09:37 UTC, inmantaci commented
Processing this pull request

2021-04-12 09:38 UTC, inmantaci commented
Merged into branches master in 3890369b25a0c55e61e090a1f64cae9baacf0fc3

2021-04-12 09:38 UTC, closed without merging

2021-04-12 09:49 UTC, inmantaci commented
Processing #2851.