Move dev getting started guide to model developers dir
inmanta/inmanta-core pull request #2868
Opened 2021-04-20 14:59 UTC by Pouriya-Inmanta

# Description

* Moved the developer getting started guide to model developers directory based on my chat with Wouter *

2021-04-20 15:00 UTC, bartv approved these changes

2021-04-21 07:10 UTC, wouterdb approved these changes

2021-04-21 07:11 UTC, wouterdb commented on changelogs/unreleased/move-developer-started-guide.yml
> +    feature: "{{description}}"
I don't think this requires a changelog entry.

2021-04-21 07:12 UTC, wouterdb requested changes
I don't think this requires a changelog entry, as the getting-started has not been released yet.

2021-04-21 09:09 UTC, wouterdb commented on changelogs/unreleased/move-dev-getting-started-guide.yml
> +sections: {}
....

2021-04-21 09:21 UTC, wouterdb requested changes
changelog is empty

2021-04-21 10:13 UTC, wouterdb approved these changes

2021-04-21 10:15 UTC, merged