Small doc improvement
inmanta/inmanta-core pull request #2881
Opened 2021-04-23 13:45 UTC by bartv

# Description

Small documentation improvement

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2021-04-23 14:08 UTC, wouterdb approved these changes

2021-04-23 15:23 UTC, arnaudsjs requested changes

2021-04-23 15:23 UTC, arnaudsjs commented on changelogs/update-install-docs.yml
> +issue-nr: 181
This PR doesn't have an issue number, is it?

2021-04-26 11:51 UTC, arnaudsjs approved these changes

2021-04-26 11:56 UTC, inmantaci commented
Processing this pull request

2021-04-26 11:56 UTC, inmantaci commented
Pull request rejected by merge tool. No change entry file found

2021-04-26 12:23 UTC, inmantaci commented
Processing this pull request

2021-04-26 12:24 UTC, inmantaci commented
Merged into branches master in 220c400d2bd11ce3a6cc865aa8932f4cd3e53c45

2021-04-26 12:24 UTC, closed without merging

2021-04-26 12:35 UTC, inmantaci commented
Processing #2885.