Issue/2919 datetime aware
inmanta/inmanta-core pull request #2953
Opened 2021-05-19 13:03 UTC by sanderr

# Description

- Makes everything internal timezone-aware
- API input accepts both timezone-aware and naive timestamps. Naive timestamps are assumed to be in UTC. Same for Python client input.
- API output returns naive timestamps in UTC.

closes #2919
closes #2896

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2021-05-19 14:35 UTC, bartv approved these changes

2021-05-19 14:43 UTC, wouterdb approved these changes

2021-05-20 08:52 UTC, arnaudsjs requested changes

2021-05-20 09:24 UTC, sanderr commented on src/inmanta/server/services/paramservice.py
> +                .isoformat(timespec="microseconds"),
That's a good suggestion, I'll see what abstractions I can make.

2021-05-20 10:15 UTC, sanderr commented on src/inmanta/server/services/paramservice.py
> +                .isoformat(timespec="microseconds"),
Is it better now?

2021-05-20 11:30 UTC, arnaudsjs requested changes

2021-05-20 11:30 UTC, arnaudsjs commented on src/inmanta/server/agentmanager.py
> +            "servertime": datetime.now().astimezone(timezone.utc).replace(tzinfo=None).isoformat(timespec="microseconds"),
```suggestion
            "servertime": datetime_utc_isoformat(datetime.now())
```

2021-05-20 11:31 UTC, sanderr commented on src/inmanta/server/agentmanager.py
> +            "servertime": datetime.now().astimezone(timezone.utc).replace(tzinfo=None).isoformat(timespec="microseconds"),
Thanks, I missed that one.

2021-05-20 11:31 UTC, arnaudsjs approved these changes

2021-05-21 14:11 UTC, inmantaci commented
Processing this pull request

2021-05-21 14:11 UTC, inmantaci commented
Pull request rejected by merge tool. Failed to parse change entry file: Change entry /tmp/tmp0_3xd2xw/changelogs/unreleased/2919-datetime-aware.yml does not match pydantic schema: 1 validation error for ChangeEntry
issue
  extra fields not permitted (type=value_error.extra)

2021-05-21 14:17 UTC, inmantaci commented
Processing this pull request

2021-05-21 14:18 UTC, inmantaci commented
Merged into branches master in 2a8c1999f9a74a3511112fc5b7ce9a8bfcdcc1ac

2021-05-21 14:18 UTC, closed without merging

2021-05-21 14:32 UTC, inmantaci commented
Processing #2967.