added custom json encoders to stable API definition
inmanta/inmanta-core pull request #2972
Opened 2021-05-25 09:13 UTC by sanderr

Should I add this to the docs as well? It doesn't necessarily need to be there I think unless we still want the docs to collect all stable API elements to better keep track of them.

2021-05-25 09:19 UTC, arnaudsjs approved these changes

2021-05-25 09:31 UTC, wouterdb requested changes
I think it would be good to keep the old API in place in ISO4, as I expect more things will break due to this.

2021-05-25 09:37 UTC, sanderr commented
@wouterdb I've removed iso4 from the destination branches. I'll open a separate pull request for iso4.

2021-05-25 09:52 UTC, wouterdb approved these changes

2021-05-25 13:54 UTC, inmantaci commented
Processing this pull request

2021-05-25 13:54 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2021-05-25 14:21 UTC, sanderr commented
I've made some more changes to fix the following import loop:
```
>>> import inmanta.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/util.py", line 41, in <module>
    from inmanta.data.model import BaseModel
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/data/__init__.py", line 36, in <module>
    from inmanta import const, resources, util
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/resources.py", line 41, in <module>
    from inmanta.execute import proxy, runtime, util
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/execute/proxy.py", line 27, in <module>
    from inmanta.util import JSONSerializable
ImportError: cannot import name 'JSONSerializable' from partially initialized module 'inmanta.util' (most likely due to a circular import) (/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/util.py)
```

I didn't find a clean way to resolve it. If we want to keep top-level imports I think we need to move some code around. Let me know what you think.

2021-05-25 17:28 UTC, arnaudsjs approved these changes
Do you know why we only have this issue on master and not on iso4?

2021-05-26 08:11 UTC, sanderr commented
@arnaudsjs this issue exists on iso4 as well, I've created a separate pull request for iso4 (#2972) because Wouter mentioned it would be better to keep the old method there as well.

2021-05-26 13:44 UTC, wouterdb approved these changes

2021-05-26 14:16 UTC, inmantaci commented
Processing this pull request

2021-05-26 14:16 UTC, inmantaci commented
Merged into branches master in 609d2f3b3bc261a8abfb3b2d8a9581a09ba64b33

2021-05-26 14:16 UTC, closed without merging