Issue/refactor developer docs
inmanta/inmanta-core pull request #3021
Opened 2021-06-08 14:16 UTC by wouterdb

# Description

Refactored docs as a preparation for modules V2

```
Environment Variabes -> Move to Administrator Documentation

Model developer documentation -> add short intro pragraph 
- Developer Getting Started  -> Needs to be reviewed
- Project Creation Guide
- Module Creation Guide  -> split from `Module Developers Guide` (+V2)
- Understanding Modules -> split from `Module Developers Guide` (+V2)
- Developing Plugins -> split from `Module Developers Guide` 
- Developing South Bound Integrations  -> split from `Module Developers Guide` 
- Releaseing Modules -> split from `Module Developers Guide`  (+V2)
- Testing Modules -> rename of `Test plugins`	
- Debugging Modules -> rename of `Model debugging`	
- Model Design Guideline
```
# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [ ] ~~Type annotations are present~~
- [ ] ~~Code is clear and sufficiently documented~~
- [ ] ~~No (preventable) type errors (check using make mypy or make mypy-diff)~~
- [ ] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [ ] ~~Correct, in line with design~~
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2021-06-09 06:36 UTC, arnaudsjs requested changes

2021-06-09 06:36 UTC, arnaudsjs commented on docs/model_developers/developer_getting_started.rst
> +    git clone project_url
This makes the notation consistent with the `cd` command mentioned above.
```suggestion
    git clone <project_url>
```

2021-06-09 06:36 UTC, arnaudsjs commented on docs/model_developers/developer_getting_started.rst
> +Once you are done with creating a project, you can ``cd`` into that directory and open vs code by running:
```suggestion
Once you are done with creating a project, you can ``cd`` into that directory and open VS Code by running:
```

2021-06-09 06:36 UTC, arnaudsjs commented on docs/model_developers/developer_getting_started.rst
> +    pip install -r requirements.txt requirements.dev.txt
```suggestion
    pip install -r requirements.txt -r requirements.dev.txt
```

2021-06-09 09:25 UTC, Pouriya-Inmanta approved these changes

2021-06-10 11:57 UTC, sanderr requested changes

2021-06-10 12:02 UTC, wouterdb commented on docs/model_developers/developer_getting_started.rst
> +    pip install -r requirements.txt -r requirements.dev.txt
yes, the test_env is used by the compiler, it should manage itself. 

This is for the venv where the tests are run in (and the can be different)

We could indeed also point INMANTA_TEST_ENV to the developer venv

2021-06-10 12:03 UTC, sanderr commented on docs/model_developers/developer_getting_started.rst
> +    pip install -r requirements.txt -r requirements.dev.txt
Of course, I see. We could point the test env there but I don't think we should in general. I'm in favor of using a tempdir for the documention.

2021-06-10 12:04 UTC, sanderr approved these changes

2021-06-11 08:24 UTC, bartv approved these changes

2021-06-11 09:12 UTC, arnaudsjs approved these changes

2021-06-16 08:47 UTC, inmantaci commented
Processing this pull request

2021-06-16 08:48 UTC, inmantaci commented
Merged into branches master in 051b9ac321cd09999410d02e5c7ddb250c0dbfec

2021-06-16 08:48 UTC, closed without merging

2021-06-16 09:00 UTC, inmantaci commented
Processing #3042.