minor improvements to developer getting started docs
inmanta/inmanta-core pull request #3549
Opened 2021-12-06 17:06 UTC by sanderr

# Description

Part of #3533 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2021-12-06 18:54 UTC, wouterdb approved these changes

2021-12-07 08:43 UTC, inmantaci commented
Processing this pull request

2021-12-07 08:43 UTC, inmantaci commented
Pull request rejected by merge tool. This pull request has not been approved yet by some of the requested reviewers. Still awaiting approval from arnaudsjs

2021-12-07 08:46 UTC, arnaudsjs requested changes

2021-12-07 08:46 UTC, arnaudsjs commented on docs/model_developers/modules.rst
> +.. _moddev-module-v2:
```suggestion
.. _moddev-module-v1:
```

2021-12-07 08:54 UTC, arnaudsjs approved these changes

2021-12-07 08:59 UTC, inmantaci commented
Processing this pull request

2021-12-07 08:59 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2021-12-07 09:06 UTC, inmantaci commented
Merged into branches master in 9b0837786097e4993f14c5b43b49320a09db8094

2021-12-07 09:06 UTC, closed without merging