Added endpoint to get the details of resource with a specific version
inmanta/inmanta-core pull request #3563
Opened 2021-12-09 16:18 UTC by andraskvr

# Description

closes #3539 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2021-12-09 19:23 UTC, wouterdb approved these changes

2021-12-10 09:52 UTC, arnaudsjs requested changes

2021-12-10 09:52 UTC, arnaudsjs commented on src/inmanta/server/services/resourceservice.py
> +        )
I think we should move this logic into `data.Resource`. That way it is more reusable across different API endpoints.

2021-12-10 10:20 UTC, arnaudsjs approved these changes

2021-12-10 10:30 UTC, inmantaci commented
Processing this pull request

2021-12-10 10:30 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict.Please open a pull request for these branches separately.

2021-12-10 10:30 UTC, inmantaci commented
Merged into branches master in bd5047559a7ef9d44fb4c3201a0496663938985f

2021-12-10 10:30 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches. You can safely close this pull request and delete the source branch.

2021-12-10 10:59 UTC, closed without merging