Issue/3536  build failure fedora
inmanta/inmanta-core pull request #3603
Opened 2021-12-23 13:57 UTC by FloLey

# Description

Fixes a bug where minor version of python where wrongly set as only the first digit of multi-digits was used.

closes #3536 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2021-12-23 15:48 UTC, wouterdb approved these changes

2021-12-24 06:56 UTC, arnaudsjs requested changes

2021-12-24 06:56 UTC, arnaudsjs commented on changelogs/unreleased/3536-multi-digit-python-version.yml
> +  bugfix: "minor version of python were wrongly set"
* The `sections` element was removed.
* You can always use the `{{description}}` placeholder in any of the sections. This placeholder will be replaced with the content of the `description` element.
```suggestion
change-type: patch
issue-nr: 3536
description: Fixes a bug where minor version of python were wrongly set as only the first digit of multi-digit number was used.
destination-branches: [iso4]
sections:
  bugfix: "{{description}}"
```

2021-12-24 08:30 UTC, arnaudsjs approved these changes

2021-12-24 08:34 UTC, inmantaci commented
Processing this pull request

2021-12-24 08:34 UTC, inmantaci commented
Merged into branches iso4 in 8a9ee7f07465d416f8d1a94862964ab283ebff24

2021-12-24 08:34 UTC, closed without merging