Inmanta module add with Python package name error message
inmanta/inmanta-core pull request #3620
Opened 2022-01-04 13:38 UTC by FloLey

# Description

When using 
`inmanta module add --v2 inmanta-module-std `
it raises an error:
`Invalid inmanta module requirement: inmanta module names use '_', not '-'.`
While this is true it's not really to the point: It would be an appropriate error message for:
`inmanta module add --v2 my-module`
but in this case a more relevant error message would be to instruct the user to use the Inmanta module name instead of the Python package name. This PR adds a new error:
`Invalid Inmanta module requirement: Use the Inmanta module name instead of the Python package name`
 

closes #3556

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-01-04 14:00 UTC, sanderr requested changes
Looks good to me. Perhaps it might be slightly better still to move the raising of the exception to `inmanta.module.InmantaModuleRequirement.parse` where the other exception is raised. This way we get the improved error message not only for `inmanta module add` but for all similar cases as well.

2022-01-04 15:03 UTC, sanderr approved these changes

2022-01-07 07:59 UTC, arnaudsjs approved these changes

2022-01-07 08:33 UTC, inmantaci commented
Processing this pull request

2022-01-07 08:33 UTC, closed without merging