Enable the UI extension by default
inmanta/inmanta-core pull request #3707
Opened 2022-01-24 14:15 UTC by FloLey

# Description

Enable the UI extension by default

closes #3653 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-01-24 14:50 UTC, wouterdb approved these changes

2022-01-24 15:05 UTC, arnaudsjs requested changes
You also need to add the `extensions.cfg` file to the RPM by adding it to the `%files` section like in https://github.com/inmanta/inmanta-service-orchestrator/blob/48c1f6dfb157661ccebd62f40d5e1d78d0ee5ea6/inmanta.spec#L204.

2022-01-24 15:23 UTC, arnaudsjs approved these changes

2022-01-25 08:34 UTC, inmantaci commented
Processing this pull request

2022-01-25 08:34 UTC, inmantaci commented
Pull request rejected by merge tool. SemVer violation: branch iso5 is eligible for this change and has not diverged from one of the branches in the destination set. Applying this merge as requested would result in a version bump due to branches diverging. Since iso5 is eligible for this change, this version bump would not be in line with the SemVer semantics. Please include iso5 in the destination set.

2022-01-25 10:17 UTC, inmantaci commented
Processing this pull request

2022-01-25 10:17 UTC, inmantaci commented
Merged into branches master, iso5 in 921a60ffc5622c8074255b0aafb035b511dba937

2022-01-25 10:17 UTC, closed without merging