Added version diff api endpoint
inmanta/inmanta-core pull request #3725
Opened 2022-01-27 14:16 UTC by andraskvr

# Description

closes #3659 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-01-27 15:06 UTC, wouterdb commented on src/inmanta/server/diff.py
> +            attr_diff = self._attributes[name].compare(other._attributes[name])
I would prefer the more symmetrical solution of implementing __sub__ and __rsub__ on `Attribute` but that is probably just me. 

```
for k in other_attribute + our_attributes:
   attr_diff = self._attributes.get(name) - other._attributes.get(name)
   if attr_diff is not None:
                diff[name] = attr_diff
```

so this is just a comment, no need to change it.

2022-01-27 18:57 UTC, bartv requested changes
It is probably more useful for Sander or Arnaud to review this as well, instead of me. My main comment is a classic: methods and classes that are not dead obvious should have a comment to provide content.

Maybe even more important is adding documentation to the test case. It is far from trivial. In 2 years all context on what is tested has faded again.

2022-01-27 19:33 UTC, wouterdb approved these changes

2022-01-28 08:50 UTC, bartv approved these changes

2022-01-28 10:25 UTC, arnaudsjs requested changes

2022-01-28 10:31 UTC, arnaudsjs commented on src/inmanta/server/diff.py
> +            self._compare_value = "\n".join([str(x) for x in self._value])
Hmm. `sort_keys` has only effect on dicts. So that's not relevant.

2022-01-28 11:32 UTC, andraskvr commented on src/inmanta/server/diff.py
> +            self._compare_value = "\n".join([str(x) for x in self._value])
I see your point and made the changes to use the json serializer for the lists as well.
Is that ok with you @bartv ?

2022-01-28 11:33 UTC, bartv commented on src/inmanta/server/diff.py
> +            self._compare_value = "\n".join([str(x) for x in self._value])
that is indeed a good idea

2022-01-28 11:58 UTC, arnaudsjs approved these changes

2022-01-28 13:40 UTC, inmantaci commented
Processing this pull request

2022-01-28 13:40 UTC, inmantaci commented
An unexpected error occurred while processing this pull request. The request might have been partially processed. Caused by: Remote state does not match local state: got pull requests for branches master but change entry specifies branches iso5, master.
If this is a first stage pull request (not opened by the merge tool) this is probably caused by a race condition (inmanta/irt#650). The best way to resolve this is to make sure the merge tool can pick up this pull request again and start from a clean slate. To do this, take the following steps:
- Close all pull requests opened by the merge tool with the same source branch as this one. Be careful not to close pull requests for source branches that start with `merge-tool/`. All pull requests created by the merge tool link to this pull request so you should be able to find them mentioned here.
- Re-add the `merge-tool-ready` label to this pull request.

2022-01-28 14:14 UTC, inmantaci commented
Processing this pull request

2022-01-28 14:14 UTC, inmantaci commented
Merged into branches iso5, master in 5d656a65ec75079bc7591526307ff3661e348d85

2022-01-28 14:14 UTC, closed without merging