split off product specific part of configure agents docs
inmanta/inmanta-core pull request #3742
Opened 2022-01-31 14:04 UTC by sanderr

# Description

Split off product specific part of configure agents docs so that product docs can overwrite it.

part of #245
companion PR inmanta/inmanta-service-orchestrator#247

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-01-31 14:04 UTC, sanderr commented on docs/install/configure-agents/install-packages.inc
> +    baseurl=https://pkg.inmanta.com/inmanta-oss-stable/el8/
Is this still accurate? Should this be the cloudsmith repo?

2022-02-01 07:25 UTC, arnaudsjs requested changes

2022-02-01 07:25 UTC, arnaudsjs commented on docs/install/install-server/configure-postgres.inc
> +  sudo yum module install postgresql:13/server
```suggestion
  sudo dnf module install postgresql:13/server
```

2022-02-01 07:26 UTC, arnaudsjs requested changes

2022-02-01 07:26 UTC, arnaudsjs commented on docs/install/configure-agents/install-packages.inc
> +    sudo yum install -y inmanta-oss-agent
```suggestion
    sudo dnf install -y inmanta-oss-agent
```

2022-02-01 09:34 UTC, arnaudsjs approved these changes

2022-02-01 09:51 UTC, inmantaci commented
Processing this pull request

2022-02-01 09:51 UTC, inmantaci commented
Merged into branches iso5, master in 664e4773a473d6ef82a78b754d54efa5cc029f64

2022-02-01 09:51 UTC, closed without merging