Issue2443/improve relation depracation msg
inmanta/inmanta-core pull request #3921
Opened 2022-02-28 13:42 UTC by FloLey

# Description

The relation deprecation suggestions will print out for example:
lma::LMA.log_collector_feature [0:1] -- Collector.lma [1:1]
This commit simplifies [1:1] to [1].

closes #2443 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-02-28 13:57 UTC, sanderr approved these changes

2022-02-28 13:57 UTC, sanderr commented on changelogs/unreleased/2443-improve-relation-depracation-msg.yml
> +description: Change the relation deprecation to be more accurate.
I'd add a feature section. It's a very small improvement but an improvement but an improvement nonetheless.
```suggestion
description: Change the relation deprecation warning to be more accurate.
```

2022-02-28 13:59 UTC, arnaudsjs requested changes

2022-02-28 13:59 UTC, arnaudsjs commented on src/inmanta/parser/plyInmantaParser.py
> +    multi_right: str = "[%s:%s]" % values_right if values_right[0] != values_right[1] else "[%s]" % values_right[0]
This is two times  the same logic right after each other. I think it would be better to isolate this logic into a separate method and reuse it.

2022-03-01 09:29 UTC, arnaudsjs approved these changes

2022-03-01 09:59 UTC, inmantaci commented
Processing this pull request

2022-03-01 09:59 UTC, inmantaci commented
Merged into branches master in 2d65ec95f3f219b98786fcccd119056cea4856a5

2022-03-01 09:59 UTC, closed without merging

2022-03-01 10:13 UTC, inmantaci commented
Processing #3931.

2022-03-01 10:26 UTC, inmantaci commented
Processing #3930.

2022-03-02 10:14 UTC, inmantaci commented
Processing #3931.