Issue/remove redundant attribute error
inmanta/inmanta-core pull request #3957
Opened 2022-03-04 16:19 UTC by Hugo-Inmanta

# Description

Remove redundant attribute error

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

~~- [ ] Attached issue to pull request~~
- [x] Changelog entry
~~- [ ] Type annotations are present~~
~~- [ ] Code is clear and sufficiently documented~~
~~- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)~~
~~- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)~~
~~- [ ] Correct, in line with design~~
~~- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-03-04 16:34 UTC, sanderr approved these changes

2022-03-07 07:08 UTC, arnaudsjs requested changes

2022-03-07 07:08 UTC, arnaudsjs commented on changelogs/unreleased/remove-redundant-attribute-exception.yml
> +destination-branches: [master, iso5]
https://github.com/inmanta/inmanta-core/commit/f9246f24b55a7045222b8be8c7c271af31e02b08 was merged on iso4, so this change has to be merged on iso4 as well.

2022-03-29 14:11 UTC, arnaudsjs approved these changes

2022-03-29 14:14 UTC, inmantaci commented
Processing this pull request

2022-03-29 14:14 UTC, closed without merging

2022-03-29 14:43 UTC, inmantaci commented
Processing #4081.