Improve error message regarding index attribute missing in constructor
inmanta/inmanta-core pull request #3965
Opened 2022-03-07 14:52 UTC by arnaudsjs

# Description

* Improve the compiler error message that is given when an index attribute is missing in the constructor call.
* Fix the typing of the `Entity.get_attribute()` method.

closes #3902 

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-03-07 15:06 UTC, wouterdb approved these changes

2022-03-07 15:48 UTC, sanderr requested changes

2022-03-07 15:48 UTC, sanderr commented on src/inmanta/ast/statements/generator.py
> +                f"The relation {entity.get_full_name()}.{attribute.name} is part of an index."
```suggestion
                f"The {attribute_kind} {entity.get_full_name()}.{attribute.name} is part of an index."
```

2022-03-08 08:38 UTC, sanderr approved these changes

2022-03-08 08:41 UTC, inmantaci commented
Processing this pull request

2022-03-08 08:41 UTC, inmantaci commented
Merged into branches master in f8784bb6607759e1950c6c89fe807a825c5376bc

2022-03-08 08:41 UTC, closed without merging

2022-03-08 08:55 UTC, inmantaci commented
Processing #3970.

2022-03-08 09:08 UTC, inmantaci commented
Processing #3969.