Fix bug that makes every inmanta warning end with an empty line
inmanta/inmanta-core pull request #3976
Opened 2022-03-09 08:43 UTC by arnaudsjs

# Description

Fix bug that makes every inmanta warning end with an empty line.

closes #3951 

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-03-09 09:09 UTC, sanderr requested changes
I think `if file is not None` we need to add the newline. Otherwise we'll just concatenate all warnings in a row.

2022-03-09 09:41 UTC, arnaudsjs commented
> I think `if file is not None` we need to add the newline. Otherwise we'll just concatenate all warnings in a row.

Nice catch! When I look at this more closely, I don't see a code path where `file is not None` would evaluate to True. And if it would evaluate to True. Shouldn't we raise an exception when `file is not None` evaluates to True? I don't think it's a good idea to have dead code in our code base.

2022-03-11 09:49 UTC, inmantaci commented
Processing this pull request

2022-03-11 09:49 UTC, inmantaci commented
Merged into branches master in ecf9c571734a04487e41b184f64385edf4e6340e

2022-03-11 09:49 UTC, closed without merging

2022-03-11 10:02 UTC, inmantaci commented
Processing #3991.

2022-03-11 10:16 UTC, inmantaci commented
Processing #3990.