Fix parsing issue with MLS with embedded strings
inmanta/inmanta-core pull request #3993
Opened 2022-03-11 15:27 UTC by FloLey

Currently the parser fails to parse MLSes correctly if there is a string enclosed at the end of it.
(when we have 4 consecutive `"` like in `exec::in_shell("""grep "test"""")`
This commit fixes the regex to accept stings (opened and closed with `"`) in a MLS

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-03-11 15:49 UTC, wouterdb approved these changes
My regex fu is not sufficiently strong here.

2022-03-11 15:58 UTC, FloLey commented
If you want to play with the regex, I build it here: [https://regex101.com/r/J8kcdf/1](https://regex101.com/r/J8kcdf/1)

2022-03-11 16:04 UTC, sanderr approved these changes

2022-03-11 16:04 UTC, sanderr requested changes
I meant to request changes, oops.

2022-03-11 16:07 UTC, sanderr commented
Issue with original regex confirmed and suggestion seems to work.

2022-03-11 16:08 UTC, sanderr commented
(https://regex101.com/r/dXe4Jc/1)

2022-03-11 16:09 UTC, FloLey commented on src/inmanta/parser/plyInmantaLex.py
> +    r'"{3}(((\"([^"]+)*\")|[\s\S])*?)"{3}'
So stupid of me, I looked so hard to handle "string" when I should just accept " at the end...

But why 5 and not 4?

2022-03-11 16:11 UTC, sanderr commented on src/inmanta/parser/plyInmantaLex.py
> +    r'"{3}(((\"([^"]+)*\")|[\s\S])*?)"{3}'
I think two strings should be valid two, no? `"""echo Here, a string: """""`.

2022-03-11 16:12 UTC, FloLey commented on src/inmanta/parser/plyInmantaLex.py
> +    r'"{3}(((\"([^"]+)*\")|[\s\S])*?)"{3}'
indeed, thanks :p

2022-03-11 16:14 UTC, sanderr commented on src/inmanta/parser/plyInmantaLex.py
> +    r'"{3}(((\"([^"]+)*\")|[\s\S])*?)"{3}'
My proposal does allow for `""""""""""` to represent the mls containing 4 quotes though, that's not entirely correct  but I'm not sure how far we want to go to be robust against every edge case. @wouterdb?

2022-03-11 16:24 UTC, sanderr commented on tests/test_parser.py
> +    assert str(mls.value) == 'String: ""'
It's interesting to see how GitHub seems to have issues with identifying mls strings for syntax highlighting as well. Guess we shouldn't feel to bad then.

2022-03-11 16:25 UTC, sanderr approved these changes

2022-03-11 16:25 UTC, sanderr commented on src/inmanta/parser/plyInmantaLex.py
> +    r'"{3}(((\"([^"]+)*\")|[\s\S])*?)"{3}'
Rerequesting @wouterdb 's review for confirmation.

2022-03-14 08:56 UTC, wouterdb approved these changes

2022-03-14 08:58 UTC, inmantaci commented
Processing this pull request

2022-03-14 08:58 UTC, inmantaci commented
Merged into branches master in e5581652d25080adb3cc843699e1d22710729d1d

2022-03-14 08:58 UTC, closed without merging

2022-03-14 09:25 UTC, inmantaci commented
Processing #3996.