bad query in query resource actions
inmanta/inmanta-core pull request #4041
Opened 2022-03-22 08:50 UTC by wouterdb

# Description

This issue causes two bugs in iso5 
1. for some resources, nothing it reported in the history in the new web console
2. failure to do deploy with `Exception('Failed to determine whether resource should reload: Invalid request: Fetching resource events only makes sense when the resource is currently deploying.` 

# Problem

The underlying issue turns out two things:
1. the attribute used in the resource identity is not necessarily an attribute of that resource
2. the like query doesn't work if special character are involved.

!!! Both of these problems are likely to exist in more places. How do we follow this up. 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-03-22 08:51 UTC, bartv approved these changes

2022-03-22 10:36 UTC, arnaudsjs requested changes
A changelog message

2022-03-22 13:11 UTC, wouterdb commented on src/inmanta/data/__init__.py
> +            query += f" AND r.resource_id_value = ${parameter_index}::varchar"
thx

2022-03-22 13:29 UTC, arnaudsjs approved these changes

2022-03-22 14:04 UTC, andraskvr approved these changes

2022-03-23 10:26 UTC, inmantaci commented
Processing this pull request

2022-03-23 10:26 UTC, closed without merging

2022-03-23 10:54 UTC, inmantaci commented
Processing #4048.