Create a notification when a git pull fails during compile
inmanta/inmanta-core pull request #4047
Opened 2022-03-23 09:32 UTC by andraskvr

# Description

closes #4021 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] ~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-03-23 10:18 UTC, wouterdb approved these changes

2022-03-23 10:27 UTC, arnaudsjs requested changes

2022-03-23 10:27 UTC, arnaudsjs commented on src/inmanta/server/services/notificationservice.py
> +                await self.notify(
Shouldn't we put the `pull` error in the if-block and the error regarding a failed exporting compile in the else-block? The `pull` error is a more specific error and is a more informative error. I guess we want to give a more specific error when that's possible.

2022-03-23 10:27 UTC, arnaudsjs commented on src/inmanta/server/services/notificationservice.py
> +                    (report for report in reports if report["name"] == "Pulling updates" and len(report["errstream"]) > 0), None
Shouldn't we test the `returncode` instead. I guess we also want to raise a notification when a failed pull doesn't have anything in `errstream`.

2022-03-23 13:56 UTC, arnaudsjs approved these changes

2022-03-24 12:09 UTC, inmantaci commented
Processing this pull request

2022-03-24 12:09 UTC, inmantaci commented
Merged into branches master in c274aa476ee2f0f80c88e8187fa48c79a92d9e4a

2022-03-24 12:09 UTC, closed without merging

2022-03-24 12:37 UTC, inmantaci commented
Processing #4053.