Issue/3470 add global variable
inmanta/inmanta-core pull request #4391
Opened 2022-06-20 13:54 UTC by Hugo-Inmanta

# Description

add global variable RUNNING_TESTS to allow the following behavior:
- in production: cast unserializable items to str
- during tests: raise an exception

closes #3470 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
~~- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-06-20 14:57 UTC, Hugo-Inmanta commented on src/inmanta/agent/handler.py
> +                    kwargs[k] = str(v)
I didn't consider it, I don't have a strong opinion either and I don't know which is best in this context

2022-06-21 11:52 UTC, wouterdb approved these changes

2022-06-21 11:52 UTC, wouterdb commented on tests/conftest.py
> +@pytest.fixture(scope="function", autouse=True)
we have regretted every single autouse fixture we every introduced, I don't know what could go wrong here, but .....

2022-06-21 12:22 UTC, arnaudsjs requested changes

2022-06-21 12:22 UTC, arnaudsjs commented on src/inmanta/agent/handler.py
> +                    raise Exception(f"Fail to serialize argument for log message {k}={v}")
```suggestion
                    raise Exception(f"Failed to serialize argument for log message {k}={v}")
```

2022-06-21 12:22 UTC, arnaudsjs commented on src/inmanta/__init__.py
> +    This is enabled/disabled by the test suite when tests are ran.
```suggestion
    This is enabled/disabled by the test suite when tests are run.
```

2022-06-21 12:22 UTC, arnaudsjs commented on src/inmanta/data/model.py
> +                raise Exception(f"Fail to serialize attribute {v}")
```suggestion
                raise Exception(f"Failed to serialize attribute {v}")
```

2022-06-21 12:22 UTC, arnaudsjs commented on tests/test_handler.py
> +        assert handler.updated
Just to make sure not exception was raised.

```suggestion
        handler.execute(ctx, res, dry_run=False)
        assert ctx.status is ResourceState. deployed
        assert handler.updated
```

2022-06-21 12:22 UTC, arnaudsjs commented on tests/test_handler.py
> +        assert handler.updated
Just to make sure no exception was raised.
```suggestion
        handler.execute(ctx, res, dry_run=False)
        assert ctx.status is ResourceState. deployed
        assert handler.updated
```

2022-06-21 12:22 UTC, arnaudsjs commented on tests/test_handler.py
> +    log_contains(caplog, "inmanta.agent.handler", logging.DEBUG, "resource aa::Aa[aa,aa=aa],v=1: Calling read_resource")
Why was this line added here?

2022-06-22 05:40 UTC, arnaudsjs approved these changes

2022-06-22 06:46 UTC, inmantaci commented
Processing this pull request

2022-06-22 06:46 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict.Please open a pull request for these branches separately.

2022-06-22 06:46 UTC, inmantaci commented
Merged into branches master in b423fceb54b73138c0f9203b320bc376230280ff

2022-06-22 06:46 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches. You can safely close this pull request and delete the source branch.

2022-06-22 06:46 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2022-06-22 07:06 UTC, inmantaci commented
Processing #4404.

2022-06-24 08:20 UTC, closed without merging