Issue/4408 cache invalidation
inmanta/inmanta-core pull request #4419
Opened 2022-06-22 15:26 UTC by wouterdb

# Description

More precise  invalidation for the compiler cache
closes #4408 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design

2022-06-22 15:40 UTC, sanderr commented on src/inmanta/parser/cache.py
> +class CacheEnveloppe:
```suggestion
class CacheEnvelope:
```
Two p's is the Dutch word.

2022-06-22 15:44 UTC, sanderr commented on src/inmanta/parser/cache.py
>                  return None
Is this still relevant? I think we can just consider the envelope timestamp the authority and ignore the cache mtime altogether.

2022-06-22 15:44 UTC, sanderr commented on src/inmanta/parser/cache.py
>                  return None
Or is this meant as a performance boost in the most common scenario so we don't need to read the file?

2022-06-22 15:46 UTC, sanderr commented on tests/compiler/test_parser_cache.py
> +    Copyright 2018 Inmanta
```suggestion
    Copyright 2022 Inmanta
```

2022-06-22 15:47 UTC, sanderr commented on tests/compiler/test_parser_cache.py
> +    # don't know hit count, may very on previous testcases
```suggestion
    # don't know hit count, may vary on previous testcases
```
Might not be what you meant. If not, I don't understand.

2022-06-22 15:53 UTC, wouterdb commented on src/inmanta/parser/cache.py
> +class CacheEnveloppe:
done

2022-06-23 05:54 UTC, arnaudsjs requested changes

2022-06-23 05:54 UTC, arnaudsjs commented on src/inmanta/parser/cache.py
> +    """Every cached file gets the exact modification to of the file it is caching, to have cheap, accurate invalidation"""
```suggestion
    """Every cached file gets the exact modification time of the file it is caching, to have cheap, accurate invalidation"""
```

2022-06-23 05:54 UTC, arnaudsjs commented on src/inmanta/parser/cache.py
> +    def __init__(self, timestamp: float, statements: List[Statement]):
```suggestion
    def __init__(self, timestamp: float, statements: List[Statement]) -> None:
```

2022-06-23 07:09 UTC, arnaudsjs approved these changes

2022-06-23 07:41 UTC, sanderr approved these changes

2022-06-23 08:09 UTC, inmantaci commented
Processing this pull request

2022-06-23 08:09 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2022-06-23 12:34 UTC, inmantaci commented
Merged into branches master in 105291f8a682efbac46a43c9b8cde690cb775ab6

2022-06-23 12:34 UTC, closed without merging