Store .cfc files in the root of the inmanta project
inmanta/inmanta-core pull request #4424
Opened 2022-06-23 11:53 UTC by arnaudsjs

# Description
The compiler cache (`.cfc`) files are now stored in the `.cfcache` directory in the root of the inmanta project instead of in the `__cfcache__` directory in the inmanta modules.

closes #4407 

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-06-23 11:54 UTC, arnaudsjs commented on changelogs/unreleased/4407-move-cfcache-files-to-project-root.yml
> +destination-branches: [master, iso5, iso4]
Do we merge this on ISO4?

2022-06-23 12:06 UTC, wouterdb approved these changes

2022-06-23 12:06 UTC, wouterdb commented on src/inmanta/parser/cache.py
> +        cache_folder = os.path.join(self.root_cache_dir, *namespace.get_full_name().split("::"))
```suggestion
        cache_folder = os.path.join(self.root_cache_dir, *namespace.to_path())
```

2022-06-23 13:02 UTC, sanderr requested changes

2022-06-23 13:06 UTC, sanderr approved these changes

2022-06-24 06:55 UTC, arnaudsjs commented
@sanderr I am re-requesting review because I had to make some change to make the test pass and resolve merge conflicts.

2022-06-24 07:33 UTC, sanderr approved these changes

2022-06-24 07:35 UTC, inmantaci commented
Processing this pull request

2022-06-24 07:35 UTC, inmantaci commented
Failed to merge changes into iso5 due to merge conflict.Please open a pull request for these branches separately.

2022-06-24 07:35 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict.Please open a pull request for these branches separately.

2022-06-24 07:35 UTC, inmantaci commented
Merged into branches master in 25c3174179a04cbec86a396b4505bf65ddece2d9

2022-06-24 07:35 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches. You can safely close this pull request and delete the source branch.

2022-06-24 07:36 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2022-06-24 08:58 UTC, closed without merging