dropped dependency on requests[chardet]
inmanta/inmanta-core pull request #4467
Opened 2022-06-28 07:35 UTC by sanderr

# Description

With the context given in https://github.com/psf/requests/issues/6177#issuecomment-1168148782, I think it should be safe to drop this requirement again. Do you agree?

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-06-28 11:26 UTC, arnaudsjs requested changes

2022-06-28 11:26 UTC, arnaudsjs commented on tests/test_app.py
> +    assert any(["already exists" in error for error in stderr])
With these brackets it looks weird to me.
```suggestion
    assert any("already exists" in error for error in stderr)
```

2022-06-28 11:41 UTC, arnaudsjs approved these changes

2022-06-28 12:02 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict.Please open a pull request for these branches separately.

2022-06-28 12:02 UTC, inmantaci commented
Merged into branches master in e34829f5170588af3d6f6cd365ab15b3d9a34e18

2022-06-28 12:02 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches. You can safely close this pull request and delete the source branch.

2022-06-28 12:22 UTC, inmantaci commented
Processing #4472.

2022-07-05 07:44 UTC, sanderr commented
Merged in iso4 in 03997ced

2022-07-05 07:44 UTC, closed without merging