Add support to enable/disable strict dependency checking (iso5)
inmanta/inmanta-core pull request #4525
Opened 2022-07-06 09:15 UTC by arnaudsjs

# Description

**Same PR as #4516 but now applied on the ISO5 branch. The only difference is that this PR disables strict dependency checking by default, while #4516 has it enabled by default.**

This PR add support to enable/disable strict dependency checking in the compiler and in the module tools. 

Closes #4409

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-07-06 12:00 UTC, sanderr requested changes
Two questions more than change requests.

2022-07-07 08:52 UTC, arnaudsjs commented on changelogs/unreleased/4409-add-support-disable-strict-checking.yml
> +  minor-improvement: "{{description}}"
I am also sure about this. I will add it, but I think it would be better to make this a deprecation-note or other-note instead of an upgrade-note.

2022-07-07 08:55 UTC, sanderr commented on changelogs/unreleased/4409-add-support-disable-strict-checking.yml
> +  minor-improvement: "{{description}}"
Fine by me.

2022-07-07 12:12 UTC, sanderr approved these changes

2022-07-07 12:31 UTC, inmantaci commented
Processing this pull request

2022-07-07 12:31 UTC, closed without merging