issue/4651-improve-log-pip
inmanta/inmanta-core pull request #4869
Opened 2022-09-20 15:19 UTC by FloLey

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-09-28 09:04 UTC, FloLey commented on src/inmanta/env.py
> +        logger = LOGGER if not "pip" in cmd else LOGGER_PIP
maybe this is to sloppy?

2022-09-28 11:34 UTC, arnaudsjs requested changes

2022-09-28 11:34 UTC, arnaudsjs commented on src/inmanta/env.py
> +                            log_msg.extend(indent(line.strip() + "\n", 2 * indentation))
```suggestion
                    for line in f:
                        if line.strip():
                            log_msg.extend(indent(line.strip() + "\n", 2 * indentation))
```

2022-09-29 09:18 UTC, FloLey commented
@arnaudsjs I'm not sure I took your all your comments (correctly) into account. Is this what you had in mind about logging "at once with the command"?

2022-09-29 11:35 UTC, arnaudsjs approved these changes

2022-09-30 13:59 UTC, Hugo-Inmanta approved these changes

2022-09-30 14:00 UTC, inmantaci commented
Pull request rejected by merge tool. Multiple change entry files found (changelogs/unreleased/1190-bytecompile.yml,changelogs/unreleased/1291-irt-archive-mypy-stdout.yml,changelogs/unreleased/4277-partial-compile-doc.yml,changelogs/unreleased/4384-regular-timeouts-on-core-tests.yml,changelogs/unreleased/4398-fix-agent-restart-storm.yml,changelogs/unreleased/4398-improved-agent-manager-logging.yml,changelogs/unreleased/4401-resource-actions-join-table.yml,changelogs/unreleased/4402-resource-actions-joint-table.yml,changelogs/unreleased/4412-put-partial-dynamic-version-allocation.yml,changelogs/unreleased/4479-doc-test-db-migration-scripts.yml,changelogs/unreleased/4497-add-support-for-extras.yml,changelogs/unreleased/4500-improve-module-install-logging.yml,changelogs/unreleased/4589-convert-a-v1-module-to-a-v2-with-the-presence-of-a-setuppy-file.yml,changelogs/unreleased/4620-fix-log-project-install.yml,changelogs/unreleased/4636-dependabot.yml,changelogs/unreleased/4642-dependabot.yml,changelogs/unreleased/4643-dependabot.yml,changelogs/unreleased/4651-improve-pip-logging.yml,changelogs/unreleased/4652-dependabot.yml,changelogs/unreleased/4653-dependabot.yml,changelogs/unreleased/4674-dependabot.yml,changelogs/unreleased/4675-dependabot.yml,changelogs/unreleased/4684-keep-requirements-v1tov2.yml,changelogs/unreleased/4688-influxdb_metrics_are_typed_inconsistently.yml,changelogs/unreleased/4699-dependabot.yml,changelogs/unreleased/4708-dependabot.yml,changelogs/unreleased/4709-dependabot.yml,changelogs/unreleased/4713-venv-inheritance-no-pythonpath.yml,changelogs/unreleased/4714-fix-empty-string-VirtualEnv.yml,changelogs/unreleased/4715-dependabot.yml,changelogs/unreleased/4718-uninstall-inmanta-pkgs.yml,changelogs/unreleased/4722-fix-wait-condition-autostartedagentmgr.yml,changelogs/unreleased/4723-fix--override-pip-extra-index-url.yml,changelogs/unreleased/4730-dependabot.yml,changelogs/unreleased/4750-dependabot.yml,changelogs/unreleased/4754-dependabot.yml,changelogs/unreleased/4755-dependabot.yml,changelogs/unreleased/4761-venv-check-bis.yml,changelogs/unreleased/4761-venv-check.yml,changelogs/unreleased/4768-dependabot.yml,changelogs/unreleased/4781-compiler-service-doesnt-log-consistently-in-same-timezone.yml,changelogs/unreleased/4782-dependabot.yml,changelogs/unreleased/4789-dependabot.yml,changelogs/unreleased/4790-dependabot.yml,changelogs/unreleased/4795-fix-security-issue.yml,changelogs/unreleased/4796-dependabot.yml,changelogs/unreleased/4797-dependabot.yml,changelogs/unreleased/4803-compiler-service-notification.yml,changelogs/unreleased/4812-dependabot.yml,changelogs/unreleased/4831-dependabot.yml,changelogs/unreleased/4834-acquire-lock-on-correct-db-table.yml,changelogs/unreleased/4859-dependabot.yml,changelogs/unreleased/4861-dependabot.yml,changelogs/unreleased/bump-compiler-version-2022-4.yml,changelogs/unreleased/compiler-test-performance.yml,changelogs/unreleased/compilerloglevels.yml,changelogs/unreleased/convert-module-tag-build.yml,changelogs/unreleased/db-dump-tool-sql-extension.yml,changelogs/unreleased/db-enum-inconsistency.yml,changelogs/unreleased/ensure-reset-of-env-settings.yml,changelogs/unreleased/fix-bugs-in-merge-partial-compile.yml,changelogs/unreleased/fix-cleanup-editable-installs-in-test-suite.yml,changelogs/unreleased/fix-db-dump-rename.yml,changelogs/unreleased/fix-incorrect-assignment-modulev2metadata.yml,changelogs/unreleased/fix-race-in-test-autostart-mapping-update-uri.yml,changelogs/unreleased/fix-test-case-resource-ordering.yml,changelogs/unreleased/fix-test-case-test-compile-runner.yml,changelogs/unreleased/fix-test-case-warnings.yml,changelogs/unreleased/fix-tests-sys-meta-path.yml,changelogs/unreleased/fix-type-assignment.yml,changelogs/unreleased/improve-logs-query-performance.yml,changelogs/unreleased/improve-query-performance.yml,changelogs/unreleased/improved_warning_assertions.yml,changelogs/unreleased/pep660-increased-compatibility.yml,changelogs/unreleased/remove-model-exporter.yml,changelogs/unreleased/remove-test-warning.yml,changelogs/unreleased/scheduler_backward_compatibility.yml,changelogs/unreleased/set-git-askpass-env-var.yml,changelogs/unreleased/use-snippetcompiler-clean-fixture.yml). This may happen when a change entry was removed from the remote repository due to a reverted change. In that case, make sure the latest changes from origin/master are merged into issue/4651-improve-log-pip before triggering merge bot.

2022-10-03 08:35 UTC, inmantaci commented
Processing this pull request

2022-10-03 08:35 UTC, inmantaci commented
Merged into branches master in 255983bdc4a4985c38cb1f81c2ccc458736b6ba1

2022-10-03 08:35 UTC, closed without merging

2022-10-03 08:54 UTC, inmantaci commented
Processing #4930.