Fix small issues on agent shutdown and deploy cancellation
inmanta/inmanta-core pull request #4932
Opened 2022-10-03 13:33 UTC by arnaudsjs

# Description

1. Fix issue where a version in the AgentCache gets closed twice when an agent is stopped (See comment in cache.py)
3. Fix issue where a ResourceAction remains present in memory after cancellation (the if-branch at line 229 of the agent.py was not setting running to False again)

# Self Check:

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-10-04 08:10 UTC, sanderr requested changes
I'm not very familiar with this code. That said, these changes seem good to me.

One small thing: since this seemed adjacent to the lsm test failure I thought I'd see if it might be resolved with these changes. I get the following error:
```
>       self._cache = AgentCache()
E       TypeError: __init__() missing 1 required positional argument: 'agent_instance'

/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/agent/agent.py:538: TypeError
```
It looks like you forgot to update some uses of the `AgentCache` constructor.

2022-10-04 12:46 UTC, arnaudsjs commented
> It looks like you forgot to update some uses of the `AgentCache` constructor.

Indeed. It's fixed now.

2022-10-04 12:52 UTC, wouterdb approved these changes

2022-10-04 12:54 UTC, sanderr approved these changes

2022-10-04 12:56 UTC, sanderr commented
Alas, I'm still getting the timeouts on lsm, I really thought this might fix it.

2022-10-04 12:59 UTC, inmantaci commented
Processing this pull request

2022-10-04 12:59 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick dde6cf536402047e3c2ece5a20e7183b8aa1a069).

2022-10-04 12:59 UTC, inmantaci commented
Merged into branches master in dde6cf536402047e3c2ece5a20e7183b8aa1a069

2022-10-04 12:59 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches by cherry-picking the relevant commit. You can safely close this pull request and delete the source branch.

2022-10-04 12:59 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2022-10-04 13:18 UTC, inmantaci commented
Processing #4940.

2022-10-05 06:11 UTC, bartv approved these changes

2022-10-05 06:43 UTC, closed without merging