Test issue
inmanta/inmanta-core pull request #5031
Opened 2022-10-25 09:18 UTC by FloLey

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-10-25 15:02 UTC, wouterdb approved these changes

2022-10-26 05:55 UTC, arnaudsjs requested changes

2022-10-26 05:55 UTC, arnaudsjs commented on changelogs/unreleased/fix-optional-field-no-default.yml
> +destination-branches: [master, iso5]
This issue is present in the release, so we need to add a bugfix section for it.

2022-10-26 07:08 UTC, arnaudsjs approved these changes

2022-10-26 07:24 UTC, inmantaci commented
Processing this pull request

2022-10-26 07:24 UTC, inmantaci commented
Merged into branches master in 6739e3bc1cdc25a8dc595709ee658226f636d2d9

2022-10-26 07:24 UTC, closed without merging

2022-10-26 07:44 UTC, inmantaci commented
Processing #5039.