Fix issue used port
inmanta/inmanta-core pull request #5189
Opened 2022-11-29 10:37 UTC by FloLey

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2022-11-30 06:16 UTC, arnaudsjs approved these changes

2022-11-30 06:37 UTC, arnaudsjs requested changes
* I did a grep for `Server()` in out test suite and it seems we have a lot more occurrences of this issue than the two instances fixed in this PR. Do you also fix these?
* I think it would be convenient to create a new fixture that 1) Creates the `Server()` instance, 2) Sets the config in place, 3) yields the server object and 4) in its tear down executes the `server.stop()` method. Or something similar if you see a better abstraction. This way we prevent code duplication and we have guarantees that all config is applied consistently everywhere.

2022-11-30 14:27 UTC, FloLey commented
@arnaudsjs I think I should not add a new fixture as there are already quit a few that do similar things. I changed my current solution to use one of those existing fixtures. Do you like it this way?

2022-11-30 14:41 UTC, arnaudsjs commented
> @arnaudsjs I think I should not add a new fixture as there are already quit a few that do similar things. I changed my current solution to use an existing helper function (not sure why it isn't a fixture?). Do you like it this way? (I found it by looking at test that were still calling `Server() `)

Nice. I didn't know we already had this functionality. The advantage of using a fixture is that you can include teardown code in the fixture as well. But for me it doesn't have to be a fixture.

2022-11-30 15:32 UTC, Hugo-Inmanta approved these changes
Looks good to me :+1:

2022-12-02 07:57 UTC, arnaudsjs requested changes
The test case `test_2151_method_header_parameter_in_body` in `tests/test_protocol.py` needs this fix as well, no?

2022-12-02 08:43 UTC, arnaudsjs approved these changes

2022-12-02 08:47 UTC, FloLey commented on changelogs/unreleased/issue-test-using-used-port.yml
> +destination-branches: [master, iso6, iso5, iso4]
@sanderr is this right?

2022-12-02 09:01 UTC, sanderr commented on changelogs/unreleased/issue-test-using-used-port.yml
> +destination-branches: [master, iso6, iso5, iso4]
```suggestion
destination-branches: [master, iso6, iso5]
```
See slack.

2022-12-02 09:45 UTC, inmantaci commented
Processing this pull request

2022-12-02 09:45 UTC, inmantaci commented
Merged into branches master, iso6 in 6f84280257f76136e2c8f1e9f390c5e230950f4d

2022-12-02 09:45 UTC, closed without merging

2022-12-02 10:06 UTC, inmantaci commented
Processing #5201.