Merge docs
inmanta/inmanta-core pull request #5279
Opened 2022-12-19 12:21 UTC by bartv

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2022-12-19 15:00 UTC, arnaudsjs requested changes

2022-12-19 15:26 UTC, bartv commented on docs/install/1-install-server.rst
> +        sudo systemctl enable --now postgresql-13
yes, you can check the mgmt server. When you install from the postgresql website, everything has the version as suffix

2022-12-19 15:27 UTC, bartv commented on docs/install/2-install-server-with-docker.rst
> +Then bring the containers up by running the following command:
yes, good catch. Fixed.

2022-12-19 15:28 UTC, arnaudsjs approved these changes

2022-12-19 15:47 UTC, inmantaci commented
Processing this pull request

2022-12-19 15:47 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2022-12-20 09:04 UTC, inmantaci commented
Processing this pull request

2022-12-20 09:04 UTC, inmantaci commented
Failed to merge changes into iso5 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 5e4516e5e54894aa02df6ffe9eee0942bee8e8a7).

2022-12-20 09:04 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 5e4516e5e54894aa02df6ffe9eee0942bee8e8a7).

2022-12-20 09:04 UTC, inmantaci commented
Merged into branches master, iso6 in 5e4516e5e54894aa02df6ffe9eee0942bee8e8a7

2022-12-20 09:04 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches by cherry-picking the relevant commit. You can safely close this pull request and delete the source branch.

2022-12-20 09:05 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2022-12-20 15:08 UTC, closed without merging