Update incremental deploy wrt to deploying
inmanta/inmanta-core pull request #5435
Opened 2023-01-26 15:20 UTC by wouterdb

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2023-01-27 11:10 UTC, sanderr requested changes

2023-01-27 12:09 UTC, sanderr requested changes

2023-01-27 12:09 UTC, sanderr commented on src/inmanta/data/__init__.py
> +                if status in [ResourceState.available.name, ResourceState.deploying.name]:
This should be reverted I think.
```suggestion
                if status == ResourceState.available.name:
```

2023-01-27 12:54 UTC, arnaudsjs approved these changes

2023-01-27 13:55 UTC, wouterdb commented on src/inmanta/data/__init__.py
> +                elif status in [ResourceState.deploying.name]:
```suggestion
                elif status == ResourceState.deploying.name:
```

2023-01-27 13:55 UTC, wouterdb commented on src/inmanta/data/__init__.py
> +                # available : next version
```suggestion
                # available -> next version
```

2023-01-30 13:02 UTC, sanderr approved these changes

2023-01-31 08:49 UTC, Hugo-Inmanta approved these changes

2023-01-31 08:51 UTC, inmantaci commented
Processing this pull request

2023-01-31 08:51 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 0485284001dac97f692ffe8d398809a7eea95934).

2023-01-31 08:51 UTC, inmantaci commented
Merged into branches master, iso6 in 0485284001dac97f692ffe8d398809a7eea95934

2023-01-31 08:51 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches by cherry-picking the relevant commit. You can safely close this pull request and delete the source branch.

2023-01-31 08:51 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2023-01-31 09:11 UTC, inmantaci commented
Processing #5456.

2023-01-31 12:42 UTC, closed without merging