added changelog template
inmanta/inmanta-core pull request #5608
Opened 2023-02-21 14:38 UTC by wouterdb

# Description

Added  changelog template

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [x] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2023-02-21 15:26 UTC, sanderr reviewed
I like how you checked the "changelog entry" checkmark in the PR template!

2023-02-21 15:30 UTC, arnaudsjs requested changes

2023-02-21 15:30 UTC, arnaudsjs commented on changelogs/template.yml
> +  other-note: "note"
Isn't this easier. In many cases you want to use the description. Then you just have to remove the lines you don't need.
```suggestion
  feature: "{{description}}"
  minor-improvement: "{{description}}"
  bugfix: "{{description}}"
  known-issue: "{{description}}"
  upgrade-note: "{{description}}"
  deprecation-note: "{{description}}"
  other-note: "{{description}}"
```

2023-02-21 15:30 UTC, arnaudsjs commented on changelogs/template.yml
> +change-type: patch
```suggestion
change-type: >"fill in"
```

2023-02-21 15:33 UTC, arnaudsjs approved these changes

2023-02-22 09:03 UTC, FloLey approved these changes

2023-02-23 10:04 UTC, Hugo-Inmanta approved these changes

2023-02-23 10:21 UTC, inmantaci commented
Processing this pull request

2023-02-23 10:21 UTC, inmantaci commented
Merged into branches master, iso6 in 0cc19ea55058f19e771c2de36a1a02c7e1f40f7e

2023-02-23 10:21 UTC, closed without merging

2023-02-23 10:40 UTC, inmantaci commented
Processing #5629.