Issue/892 vs cde support workspace adr
inmanta/inmanta-core pull request #5756
Opened 2023-03-28 12:01 UTC by Hugo-Inmanta

# Description

Add ADR

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [x] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2023-03-28 12:07 UTC, Hugo-Inmanta commented on docs/adr/0003-workspace-support-vscode-extension.md
> +* Deciders: [Sander, Hugo]
@sanderr I included you because you helped me quite a lot fleshing out the desired behaviour, should I include anyone else ?

2023-03-28 14:56 UTC, sanderr commented on docs/adr/0003-workspace-support-vscode-extension.md
> +be a desired behaviour in some cases, but is not acceptable in most cases. The issue of incompatible requirements would
And possibly even different Python / compiler versions.

2023-03-29 06:02 UTC, arnaudsjs requested changes

2023-03-29 06:05 UTC, Hugo-Inmanta commented on docs/adr/0003-workspace-support-vscode-extension.md
I thought all ADR's were centralized in this one place, makes more sense to me to put it in the vscode repo indeed :+1:

2023-03-29 06:50 UTC, Hugo-Inmanta commented on docs/adr/0003-workspace-support-vscode-extension.md
> +When a `.cf` file is opened, if the folder it belongs to is not already being managed by a language server, then we
I agree, I like this approach which is more user-friendly. I'll implement it and change the ADR

2023-03-29 06:52 UTC, sanderr commented on docs/adr/0003-workspace-support-vscode-extension.md
@Hugo-Inmanta I actually think you're right that we decided that we'd centralize all adrs in one repo. Perhaps we can quickly ask the question at the stand up.

2023-03-30 11:34 UTC, arnaudsjs commented on docs/adr/0003-workspace-support-vscode-extension.md
> +NOTE: A check is performed to make sure the interpreted used is not a globally installed one
```suggestion
NOTE: A check is performed to make sure the interpreter used is not a globally installed one
```

2023-03-30 11:37 UTC, arnaudsjs commented on docs/adr/0003-workspace-support-vscode-extension.md
> +NOTE: A check is performed to make sure the interpreted used is not a globally installed one
If we mention this corner case here, I would also describe how we handle it.

2023-03-31 06:50 UTC, arnaudsjs approved these changes

2023-03-31 09:42 UTC, Hugo-Inmanta commented
As discussed, this adr should go into the vs-code extension repo. This adr has been added as a part of this [PR](https://github.com/inmanta/vscode-inmanta/pull/1061)

2023-03-31 09:42 UTC, closed without merging