Produce no warning about download path if it is not used
inmanta/inmanta-core pull request #5779
Opened 2023-03-30 14:08 UTC by wouterdb

# Description

Produce no warning about download path if it is not used

closes #5507 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2023-03-30 14:32 UTC, FloLey approved these changes

2023-03-31 06:48 UTC, arnaudsjs requested changes

2023-03-31 06:48 UTC, arnaudsjs commented on src/inmanta/module.py
> +        return true of this repo will never produce any repo
```suggestion
        Return true if this repo will never produce any repo.
```

2023-03-31 09:09 UTC, arnaudsjs approved these changes

2023-03-31 09:31 UTC, inmantaci commented
Processing this pull request

2023-03-31 09:31 UTC, inmantaci commented
Failed to merge changes into iso5 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick bedab7a9612e0b88d04f744e05dee0ed81848948).

2023-03-31 09:31 UTC, inmantaci commented
Merged into branches master, iso6 in bedab7a9612e0b88d04f744e05dee0ed81848948

2023-03-31 09:31 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2023-03-31 19:03 UTC, closed without merging