Fixed bug in resource.version
inmanta/inmanta-core pull request #5934
Opened 2023-04-28 14:17 UTC by wouterdb

# Description

Ensure  resource.version == resource.id.version

closes #5931

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2023-04-28 14:28 UTC, sanderr approved these changes

2023-05-02 06:11 UTC, arnaudsjs requested changes

2023-05-03 05:52 UTC, arnaudsjs approved these changes

2023-05-03 07:15 UTC, inmantaci commented
Processing this pull request

2023-05-03 07:15 UTC, inmantaci commented
Failed to merge changes into iso5 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 28acbdd5d4c8030507bd4ff125ece715e7a66699).

2023-05-03 07:15 UTC, inmantaci commented
Failed to merge changes into iso4 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 28acbdd5d4c8030507bd4ff125ece715e7a66699).

2023-05-03 07:15 UTC, inmantaci commented
Merged into branches master in 28acbdd5d4c8030507bd4ff125ece715e7a66699

2023-05-03 07:15 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches by cherry-picking the relevant commit. You can safely close this pull request and delete the source branch.

2023-05-03 07:15 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2023-05-03 07:32 UTC, inmantaci commented
Processing #5945.

2023-05-03 09:09 UTC, wouterdb commented
moved to #5947

2023-05-03 09:09 UTC, closed without merging