Issue/auto comment lines dump tool
inmanta/inmanta-core pull request #6029
Opened 2023-05-24 08:45 UTC by arnaudsjs

# Description

Make the dump_tool automatically comments out all undesired lines in the generated database dump to prevents issues with trailing white-spaces being removed from the file.

# Self Check:

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2023-05-24 09:28 UTC, sanderr approved these changes

2023-05-24 13:14 UTC, Hugo-Inmanta requested changes

2023-05-24 13:14 UTC, Hugo-Inmanta commented on tests/db/migration_tests/dump_tool.py
> +        fh.writelines(all_lines)
This should go I think ?
```suggestion

```

2023-05-25 08:43 UTC, arnaudsjs commented on tests/db/migration_tests/dump_tool.py
> +        fh.writelines(all_lines)
Nice catch. Thanks!

2023-05-25 08:44 UTC, Hugo-Inmanta approved these changes

2023-05-25 09:59 UTC, inmantaci commented
Processing this pull request

2023-05-25 09:59 UTC, inmantaci commented
Failed to merge changes into iso5 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 7c8e19c2f9c79dd67c1387526d3631b6022531fd).

2023-05-25 09:59 UTC, inmantaci commented
Merged into branches master in 7c8e19c2f9c79dd67c1387526d3631b6022531fd

2023-05-25 10:17 UTC, inmantaci commented
Processing #6040.

2023-05-25 11:07 UTC, closed without merging