switch to mono time
inmanta/inmanta-core pull request #6542
Opened 2023-09-25 08:57 UTC by wouterdb

# Description

I observed a negative timeout here, switched to mono time 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [x] Changelog entry
- [ ] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2023-09-25 08:58 UTC, sanderr approved these changes

2023-09-25 09:08 UTC, Hugo-Inmanta requested changes

2023-09-25 09:10 UTC, Hugo-Inmanta approved these changes

2023-09-25 09:40 UTC, inmantaci commented
Processing this pull request

2023-09-25 09:40 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2023-09-25 09:51 UTC, arnaudsjs commented
@wouterdb Don't we also have to update the `time.time()` in the `seen()` method?

2023-09-26 10:00 UTC, inmantaci commented
Processing this pull request

2023-09-26 10:00 UTC, inmantaci commented
Merged into branches master in c4cd9d862cb573fe76e32870ba58745969851c91

2023-09-26 10:00 UTC, closed without merging

2023-09-26 10:19 UTC, inmantaci commented
Processing #6547.