Fix race in test for incremental deploys
inmanta/inmanta-core pull request #6565
Opened 2023-10-02 13:37 UTC by arnaudsjs

# Description

This PR fixes a race condition in the `test_s_incremental_deploy_interrupts_full_deploy` test case. The old wait condition `wait_for_done_with_waiters(client, environment, version2)` returned as soon as all resources in version2 were deployed successfully. But in fact we should wait for two deployments in version2, one incremental deploy and one repair run that v2 interrupted.

# Self Check:

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2023-10-02 14:33 UTC, Hugo-Inmanta requested changes
I was looking around a bit and this L2559 looks weird:
https://github.com/inmanta/inmanta-core/blob/e9110e68e9bd1e83e83fb2a8cc772793b236ff08/tests/agent_server/test_server_agent.py#L2559-L2561

looks good otherwise !

2023-10-03 09:19 UTC, sanderr approved these changes

2023-10-03 11:52 UTC, arnaudsjs commented
> I was looking around a bit and this L2559 looks weird:
> 
> https://github.com/inmanta/inmanta-core/blob/e9110e68e9bd1e83e83fb2a8cc772793b236ff08/tests/agent_server/test_server_agent.py#L2559-L2561
> 
> looks good otherwise !

Nice catch!

2023-10-03 11:53 UTC, Hugo-Inmanta approved these changes

2023-10-03 12:10 UTC, inmantaci commented
Processing this pull request

2023-10-03 12:10 UTC, inmantaci commented
Merged into branches master in 1850206d5cffaa9c60f10fbde6dde8b364dfe6b5

2023-10-03 12:10 UTC, closed without merging

2023-10-03 12:29 UTC, inmantaci commented
Processing #6571.