Add validation_type method from inmanta-core
inmanta/inmanta-core pull request #6572
Opened 2023-10-03 12:26 UTC by arnaudsjs

# Description

This ticket moves the `validation_type()` method from the std module to inmanta-core.

closes #6540 

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2023-10-03 12:43 UTC, sanderr requested changes
One tiny remark

2023-10-03 12:43 UTC, sanderr commented on src/inmanta/validation_type.py
> +def validate_type(fq_type_name: str, value: PrimitiveTypes, validation_parameters: Optional[dict[str, object]] = None) -> None:
```suggestion
def validate_type(fq_type_name: str, value: PrimitiveTypes, validation_parameters: Optional[abc.Mapping[str, object]] = None) -> None:
```

2023-10-03 12:49 UTC, sanderr approved these changes

2023-10-03 13:59 UTC, arnaudsjs commented on changelogs/unreleased/move-validate-type-method-to-core.yml
> +destination-branches: [master]
Once this is merged in, I will create a new PR for the ISO6 branch that also bump the `COMPILER_VERSION` on the iso6 branch.

2023-10-03 14:00 UTC, bartv approved these changes

2023-10-04 06:49 UTC, inmantaci commented
Processing this pull request

2023-10-04 06:49 UTC, inmantaci commented
Merged into branches master in bb01fff28d9de39e6fd9ee482d816ee171e3934d

2023-10-04 06:49 UTC, closed without merging