Issue/6612 fix mypy error on delete cascade method
inmanta/inmanta-core pull request #6649
Opened 2023-10-20 09:11 UTC by Hugo-Inmanta

# Description

Fixes the following mypy error:

```
$ make mypy-diff 
- src/inmanta/data/__init__.py:2843: error: Signature of "delete_cascade" incompatible with supertype "BaseDocument"  [override]
- src/inmanta/data/__init__.py:2843: note:      Superclass:
- src/inmanta/data/__init__.py:2843: note:          def delete_cascade(self, connection: Optional[Connection] = ...) -> Coroutine[Any, Any, None]
- src/inmanta/data/__init__.py:2843: note:      Subclass:
- src/inmanta/data/__init__.py:2843: note:          def delete_cascade(self, only_content: bool = ..., connection: Optional[Connection] = ...) -> Coroutine[Any, Any, None]

```

closes #6612

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2023-10-20 09:48 UTC, arnaudsjs requested changes
The `only_content` attribute only makes sense in the context of a `Project` or an `Environment`. I don't think it's a good idea to add it to the `BaseModel` level, because it will lead to confusing code. I think we have to remove the `only_content` attribute from the `delete_cascade` method and create a new method `delete_content()` for example on the `Project` and `Environment` classes that only delete the content.

2023-10-20 13:01 UTC, Hugo-Inmanta commented
Added the `clear` method for Environment. I didn't add it for Project since there was no existing use case for it.

2023-10-23 07:06 UTC, arnaudsjs approved these changes

2023-10-23 13:27 UTC, inmantaci commented
Processing this pull request

2023-10-23 13:27 UTC, inmantaci commented
Pull request rejected by merge tool. Failed to parse change entry file: Change entry /tmp/tmpyk91j133/changelogs/unreleased/6612-fix-mypy-error-on-delete-cascade-method.yml does not match pydantic schema: 1 validation error for ChangeEntry
sections
  none is not an allowed value (type=type_error.none.not_allowed)

2023-10-24 08:08 UTC, inmantaci commented
Processing this pull request

2023-10-24 08:08 UTC, inmantaci commented
Merged into branches master in 5169cc90e284358b4e2ad5987978f017aed38e08

2023-10-24 08:08 UTC, closed without merging

2023-10-24 08:28 UTC, inmantaci commented
Processing #6666.