Issue/6372 run pyupgrade python39
inmanta/inmanta-core pull request #6696
Opened 2023-10-30 13:18 UTC by Hugo-Inmanta

# Description

Run `pyupgrade --py39-plus`

Part of https://github.com/inmanta/inmanta-core/issues/6372

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2023-10-30 15:19 UTC, Hugo-Inmanta commented on tests/data/compile_138/libs/lma/plugins/__init__.py
> -from inmanta import ast
Might not be ok to remove

2023-10-30 15:19 UTC, Hugo-Inmanta commented on tests/data/modules_v2/elaboratev2module_extension/inmanta_plugins/elaboratev2module_extension/__init__.py
> -import inmanta_plugins.elaboratev2module
same

2023-10-31 07:48 UTC, bartv commented
Shouldn't we also run this in the linting phase once we are up to date?

2023-10-31 07:50 UTC, bartv commented
Based on the failed tests I also think we can only do this once we are using typeadapter instead of our own typing logic in protocol (cc @sanderr )

2023-10-31 08:52 UTC, sanderr requested changes
@Hugo-Inmanta this is going to be merge hell with the pydantic PR, that's why I put that one as a blocker. I think it's easier by far to just run this tool again once that PR is in. If you want to go ahead with the rest of the ticket you can split this task off into a separate ticket.

> Shouldn't we also run this in the linting phase once we are up to date?

I like that.

2023-10-31 08:55 UTC, Hugo-Inmanta commented
>  that's why I put that one as a blocker

Damn it, I completely missed the blockers.

2023-10-31 09:04 UTC, sanderr reviewed
Wow, this changed way more lines than I would've thought...

2023-10-31 11:23 UTC, bartv commented
@sanderr this wil only work if our protocol layer starts supporting dict and list instead of Dict and List. I do not think that is the case and TypeAdapter will solve that for us.

2023-12-05 09:49 UTC, closed without merging