update
inmanta/inmanta-core pull request #6737
Opened 2023-11-16 10:43 UTC by FloLey

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2023-11-21 08:10 UTC, arnaudsjs requested changes

2023-11-21 08:18 UTC, Hugo-Inmanta requested changes

2023-11-21 08:18 UTC, Hugo-Inmanta commented on tests/test_module_loader.py
> +        env.process_env.install_from_source([env.LocalPackagePath(path=module_path, editable=False)])
I think only the `install_from_source` is expected to raise a `ConflictingRequirements` ? If so, I would move the `build` part outside of the `with` block to make it clearer

2023-11-21 08:18 UTC, Hugo-Inmanta commented on src/inmanta/moduletool.py
> +        Build the module using the pip system config and return the path to the build artifact.
I can't find where the system's pip config is being used during the build, is this already implemented ?

2023-11-21 10:41 UTC, Hugo-Inmanta commented on src/inmanta/moduletool.py
> +        Build the module using the pip system config and return the path to the build artifact.
Ohh I see :+1:

2023-11-21 12:47 UTC, arnaudsjs requested changes

2023-11-21 12:47 UTC, arnaudsjs commented on tests/moduletool/test_install.py
> +def test_module_install(snippetcompiler_clean, modules_v2_dir: str, editable: bool) -> None:
The docstring still references the `inmanta module install` command.

2023-11-21 12:47 UTC, arnaudsjs commented on tests/moduletool/test_install.py
> +    with pytest.raises(ConflictingRequirements) as exc_info:
Docstring still references the install command.

2023-11-21 12:48 UTC, arnaudsjs commented on changelogs/unreleased/6717-update-module-install.yml
> +  build a module from source and install the distribution package, respectively."
The command for an editable install is missing here.

2023-11-21 13:13 UTC, Hugo-Inmanta approved these changes

2023-11-21 13:35 UTC, arnaudsjs requested changes

2023-11-21 13:35 UTC, arnaudsjs commented on tests/moduletool/test_install.py
> +    Make sur it is possible to install a module in both non-editable and editable mode
```suggestion
    Make sure it is possible to install a module in both non-editable and editable mode
```

2023-11-21 13:42 UTC, arnaudsjs approved these changes

2023-11-21 14:01 UTC, inmantaci commented
Processing this pull request

2023-11-21 14:01 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2023-11-22 09:12 UTC, inmantaci commented
Processing this pull request

2023-11-22 09:12 UTC, inmantaci commented
Merged into branches master in e5d85226a4495e26d42ad3c250a130763404ef17

2023-11-22 09:12 UTC, closed without merging