Add documentation on how to perform upgrade in-place
inmanta/inmanta-core pull request #6807
Opened 2023-12-04 15:18 UTC by arnaudsjs

# Description

Add documentation on how to perform an upgrade in-place.

closes inmanta/inmanta-service-orchestrator#393

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [ ] ~~Type annotations are present~~
- [ ] ~~Code is clear and sufficiently documented~~
- [ ] ~~No (preventable) type errors (check using make mypy or make mypy-diff)~~
- [ ] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2023-12-04 16:00 UTC, Hugo-Inmanta approved these changes

2023-12-06 08:59 UTC, edvgui commented on docs/administrators/upgrading_the_orchestrator.rst
> +    - Before upgrading the orchestrator to a new major version, make sure the old orchestrator is at the latest version available within its major.
Is the guide about upgrading the orchestrator to a new version or a new major version? In the case of the latter, where is the other update procedure documented?

2023-12-06 11:30 UTC, sanderr requested changes
> One thing I think we should add is a note to read the new version's changelog for any version-specific upgrade notes.

I think this is still important. Other than that I'm fine with it as is, the stopping of the server is less important imo.

2023-12-06 12:49 UTC, sanderr approved these changes

2023-12-06 15:31 UTC, inmantaci commented
Processing this pull request

2023-12-06 15:31 UTC, inmantaci commented
Merged into branches master in 956ccb81c666728a5ab7f7c222b4695f51a4c9fe

2023-12-06 15:31 UTC, closed without merging

2023-12-06 15:51 UTC, inmantaci commented
Processing #6834.