Issue/race in increment
inmanta/inmanta-core pull request #6824
Opened 2023-12-05 21:28 UTC by wouterdb

# Description

Fix for race condition, to be finished 

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2023-12-05 21:29 UTC, wouterdb commented on src/inmanta/server/services/resourceservice.py
> +        # Otherwise the agent will fail the deployment
We could fix this by considering available as deployed, but I do like this second layer of defense in the agent

2023-12-05 21:30 UTC, wouterdb commented on src/inmanta/server/services/resourceservice.py
> +        # We don't do this back propagation on deploy,
there were other reasons not to, but I forgot again @sanderr may recall

2023-12-06 10:01 UTC, arnaudsjs requested changes

2023-12-06 10:39 UTC, arnaudsjs approved these changes

2023-12-06 11:00 UTC, sanderr approved these changes
I have some questions I'd like to ask in person, but nothing blocking this.

2023-12-06 11:20 UTC, inmantaci commented
Processing this pull request

2023-12-06 11:20 UTC, inmantaci commented
Merged into branches master in f262cadcf42f12b043fa816f527182ea5251ca83

2023-12-06 11:20 UTC, closed without merging

2023-12-06 11:40 UTC, inmantaci commented
Processing #6831.