Added transaction finalizer
inmanta/inmanta-core pull request #7220
Opened 2024-02-19 15:50 UTC by wouterdb

# Description

Added transaction finalizer 
fixes #6955 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-02-19 15:50 UTC, wouterdb commented on src/inmanta/server/services/orchestrationservice.py
> +                with ConnectionInTransaction(connection) as connection_holder:
indented one level

2024-02-20 07:19 UTC, arnaudsjs requested changes

2024-02-20 07:19 UTC, arnaudsjs commented on src/inmanta/server/services/resourceservice.py
> +                # Make sure tasks are scheduled AFTER the tx is done
```suggestion
                assert model_version is not None  # mypy can't figure this out
                # Make sure tasks are scheduled AFTER the tx is done.
                # This method is only called if the transaction commits successfully.
```

2024-02-20 08:06 UTC, wouterdb commented on src/inmanta/util/db.py
> +
```suggestion

```

2024-02-20 08:06 UTC, wouterdb commented on src/inmanta/util/db.py
> +        return None
```suggestion
```

2024-02-20 08:07 UTC, wouterdb commented on src/inmanta/util/db.py
> +
removed

2024-02-20 08:07 UTC, arnaudsjs approved these changes

2024-02-20 08:28 UTC, inmantaci commented
Processing this pull request

2024-02-20 08:28 UTC, inmantaci commented
Failed to merge changes into iso6 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 1a4d26ef520fe4134ed4fb1a4b6ee6e81d6a3db3).

2024-02-20 08:28 UTC, inmantaci commented
Merged into branches master in 1a4d26ef520fe4134ed4fb1a4b6ee6e81d6a3db3

2024-02-20 08:28 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches by cherry-picking the relevant commit. You can safely close this pull request and delete the source branch.

2024-02-20 08:28 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2024-02-20 08:48 UTC, closed without merging

2024-02-20 08:56 UTC, inmantaci commented
Processing #7227.