Update docs for postgresql installation
inmanta/inmanta-core pull request #7268
Opened 2024-02-27 16:45 UTC by Hugo-Inmanta

# Description

Update docs

closes https://github.com/inmanta/inmanta-core/issues/7042

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-02-27 16:56 UTC, Hugo-Inmanta commented on docs/install/1-install-server.rst
> +you installed it on, Inmanta requires git to be installed.
I think this can go since inmanta service orchestrator server installs python 3.11

2024-02-27 16:56 UTC, Hugo-Inmanta commented on docs/install/1-install-server.rst
> +        :substitutions:
This was causing the whole block to be rendered with a leading space. That lead to some error when copy pasting this block into a config file

2024-02-27 16:56 UTC, Hugo-Inmanta commented on docs/install/1-install-server.rst
>          sudo su - postgres -c "postgresql-setup --initdb"
This step was failing with following error:
`initdb: error: invalid locale settings; check LANG and LC_* environment variables`
Which comes from the fact that the system is using a locale that is not installed:

current status of the system locales settings:
```sh
[rocky@issue-7042 ~]$ localectl status
   System Locale: LANG=en_US.UTF-8     <---- Not installed
       VC Keymap: us
      X11 Layout: us
```

Installed locales:

```sh
[rocky@issue-7042 ~]$ locale -a

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.utf8
POSIX
```


Managed to make the command work by changing to a locale that is installed :
```sh
[rocky@issue-7042 ~]$ sudo localectl set-locale LANG=C.utf8
```

An alternative fix involved installing the missing locale through 
```
[rocky@issue-7042 ~]$ sudo dnf install langpacks-en glibc-all-langpacks -y
```

Only lead I have on why this is happening is that it comes from my ssh configuration that used to have:
```txt
# file : /etc/ssh/ssh_config
#   SendEnv LANG LC_*    <-- this wasn't commented out
```

2024-02-27 16:58 UTC, Hugo-Inmanta commented
The `sudo su - postgres -c "postgresql-setup --initdb"` step was failing with following error:
`initdb: error: invalid locale settings; check LANG and LC_* environment variables`
Which comes from the fact that the system is using a locale that is not installed:

current status of the system locales settings:
```sh
[rocky@issue-7042 ~]$ localectl status
   System Locale: LANG=en_US.UTF-8     <---- Not installed
       VC Keymap: us
      X11 Layout: us
```

Installed locales:

```sh
[rocky@issue-7042 ~]$ locale -a

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.utf8
POSIX
```


Managed to make the command work by changing to a locale that is installed :
```sh
[rocky@issue-7042 ~]$ sudo localectl set-locale LANG=C.utf8
```

An alternative fix involved installing the missing locale through 
```
[rocky@issue-7042 ~]$ sudo dnf install langpacks-en glibc-all-langpacks -y
```

Only lead I have on why this is happening is that it comes from my ssh configuration that used to have:
```txt
# file : /etc/ssh/ssh_config
#   SendEnv LANG LC_*    <-- this wasn't commented out
```

2024-02-28 07:42 UTC, arnaudsjs commented
> The `sudo su - postgres -c "postgresql-setup --initdb"` step was failing with following error: `initdb: error: invalid locale settings; check LANG and LC_* environment variables` Which comes from the fact that the system is using a locale that is not installed:
> 
> current status of the system locales settings:
> 
> ```shell
> [rocky@issue-7042 ~]$ localectl status
>    System Locale: LANG=en_US.UTF-8     <---- Not installed
>        VC Keymap: us
>       X11 Layout: us
> ```
> 
> Installed locales:
> 
> ```shell
> [rocky@issue-7042 ~]$ locale -a
> 
> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_MESSAGES to default locale: No such file or directory
> locale: Cannot set LC_COLLATE to default locale: No such file or directory
> C
> C.utf8
> POSIX
> ```
> 
> Managed to make the command work by changing to a locale that is installed :
> 
> ```shell
> [rocky@issue-7042 ~]$ sudo localectl set-locale LANG=C.utf8
> ```
> 
> An alternative fix involved installing the missing locale through
> 
> ```
> [rocky@issue-7042 ~]$ sudo dnf install langpacks-en glibc-all-langpacks -y
> ```

I would not change the locale, because that might have other undesired side-effect on the system. So I would do for the approach that installs the langpacks. I noticed that doing

```
sudo dnf install langpacks-en -y
```

is enough to make it work on a default RHEL 9. I would not mention the `glibc-all-langpacks` package for that reason in the install docs. But I would mention in the documentation why the `langpacks-en` package is required and that a different langpack might be required based on the locale used on the users system.

2024-02-28 07:43 UTC, arnaudsjs requested changes

2024-02-28 07:45 UTC, Hugo-Inmanta commented on docs/install/1-install-server.rst
> +    Install the PostgreSQL 13 package included in RHEL. More info in the `postgresql documentation <https://www.postgresql.org/download/linux/redhat/>`_
I meant to link to the `Included in Distribution` part of the page but there's no anchor to link to :/

2024-02-28 07:51 UTC, arnaudsjs commented on docs/install/1-install-server.rst
> +    Install the PostgreSQL 13 package included in RHEL. More info in the `postgresql documentation <https://www.postgresql.org/download/linux/redhat/>`_
I see. Then I would explicitly mention the relevant section.

2024-02-28 08:16 UTC, Hugo-Inmanta commented
locale warning part renders as such: 
![image](https://github.com/inmanta/inmanta-core/assets/98876549/d09a72b0-933d-4a8b-bac4-80f67028b4de)

2024-02-28 08:34 UTC, arnaudsjs approved these changes

2024-02-28 08:34 UTC, arnaudsjs commented
> locale warning part renders as such: ![image](https://private-user-images.githubusercontent.com/98876549/308471764-d09a72b0-933d-4a8b-bac4-80f67028b4de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDg2NDAsIm5iZiI6MTcwOTEwODM0MCwicGF0aCI6Ii85ODg3NjU0OS8zMDg0NzE3NjQtZDA5YTcyYjAtOTMzZC00YThiLWJhYzQtODBmNjcwMjhiNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMTIwOTI3OGY2ZmE3ZDBkOTVjYzkzN2I5MGY0NTA2MzlhZjVhYjJiZTdiODhjNmE3NGIyNjcwY2UyOWVjYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8J5gHKiFr1_9_WzqNuUt-jZmxgvQ5iBIA8PPaQhEfhg)

With the orange warning box it looks more dramatic than what I had in mind, but the message is definitely clear.

2024-02-28 08:38 UTC, inmantaci commented
Processing this pull request

2024-02-28 08:38 UTC, inmantaci commented
Merged into branches master in d62a2a75a0062c85d3f113d8c3b166ee001a10b3

2024-02-28 08:38 UTC, closed without merging

2024-02-28 08:59 UTC, inmantaci commented
Processing #7275.