Issue/7154 compacted env vars
inmanta/inmanta-core pull request #7350
Opened 2024-03-12 13:37 UTC by wouterdb

# Description

Add the ability to have mergeable environment variables 
closes #7154 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
```
src/inmanta/data/__init__.py:5048: error: Argument 1 to "loads" has incompatible type "object"; expected "str | bytes | bytearray"  [arg-type]
src/inmanta/data/dataview.py:1122: error: Argument 1 to "loads" has incompatible type "object"; expected "str | bytes | bytearray"  [arg-type]
src/inmanta/data/dataview.py:1254: error: Argument 1 to "loads" has incompatible type "object"; expected "str | bytes | bytearray"  [arg-type]

```
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-03-12 15:18 UTC, arnaudsjs requested changes

2024-03-12 15:18 UTC, arnaudsjs commented on tests/server/test_compilerservice.py
> +    # request with partial, will no be merged
```suggestion
    # request with partial, will not be merged
```

2024-03-13 10:13 UTC, wouterdb commented on src/inmanta/server/services/compilerservice.py
> +                    merged_env_vars[key] = existing + " " + to_add
It is documented as a space separated list, so if you have spaces in the value, it is always a problem.
If you want them escaped, you should escape them I think.

2024-03-13 15:10 UTC, arnaudsjs requested changes

2024-03-13 15:22 UTC, wouterdb commented on src/inmanta/data/__init__.py
> +        out["environment_variables"] = self.used_environment_variables or self.requested_environment_variables
dang, good point

2024-03-13 16:28 UTC, wouterdb commented on src/inmanta/data/dataview.py
> +                    json.loads(compile["used_environment_variables"]) if compile["used_environment_variables"] else {}
moved to validator

2024-03-14 08:34 UTC, FloLey approved these changes

2024-03-14 12:40 UTC, inmantaci commented
Pull request rejected by merge tool. This pull request has not been approved yet.

2024-03-15 08:47 UTC, arnaudsjs requested changes

2024-03-15 08:47 UTC, arnaudsjs commented on src/inmanta/data/dataview.py
> +                    json.loads(compile["used_environment_variables"]) if compile["used_environment_variables"] else {}
```suggestion
                    json.loads(compile["used_environment_variables"]) if compile["used_environment_variables"] else None
```

2024-03-15 10:20 UTC, arnaudsjs approved these changes

2024-03-15 11:02 UTC, inmantaci commented
Processing this pull request

2024-03-15 11:02 UTC, inmantaci commented
Merged into branches master in f5ff485b3fae8fee113b0e929319d79e6787ba64

2024-03-15 11:02 UTC, closed without merging

2024-03-15 11:33 UTC, inmantaci commented
Processing #7369.