Cleanup code folder on agent restart
inmanta/inmanta-core pull request #7396
Opened 2024-03-19 16:05 UTC by wouterdb

# Description

Cleanup code folder on agent restart

closes  #7388 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [X] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-03-20 09:05 UTC, arnaudsjs requested changes
* We also need to remove the documentation that was added as part of https://github.com/inmanta/inmanta-core/commit/7e2819e27617cee72055ee6671c5de35e40bbdca
* The above-mentioned commit also added the `send_notification` API endpoint, that allows an agent to send_notifications. This PR removes the test case that verifies the behavior of this endpoint. So we should either remove the endpoint again or make sure it is properly tested.

2024-03-20 09:42 UTC, arnaudsjs approved these changes

2024-03-20 10:15 UTC, Hugo-Inmanta requested changes
Changelog entry is missing, lgtm otherwise

2024-03-20 14:17 UTC, Hugo-Inmanta approved these changes

2024-03-21 08:50 UTC, inmantaci commented
Processing this pull request

2024-03-21 08:50 UTC, inmantaci commented
Failed to merge changes into iso7 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick 90b5c296fcf2da4995b06ee0011b40beb48e44bc).

2024-03-21 08:50 UTC, inmantaci commented
Merged into branches master in 90b5c296fcf2da4995b06ee0011b40beb48e44bc

2024-03-21 08:50 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches by cherry-picking the relevant commit. You can safely close this pull request and delete the source branch.

2024-03-21 08:50 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2024-03-22 08:50 UTC, closed without merging