Add documentation about creating initial user
inmanta/inmanta-core pull request #7433
Opened 2024-03-25 14:29 UTC by arnaudsjs

# Description

Add documentation about creating the initial user when using the built-in authentication provider.

closes #7357

# Self Check:

- [x] Attached issue to pull request
- [ ] Changelog entry
- [ ] ~~Type annotations are present~~
- [ ] ~~Code is clear and sufficiently documented~~
- [ ] ~~No (preventable) type errors (check using make mypy or make mypy-diff)~~
- [ ] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2024-03-25 14:51 UTC, sanderr requested changes

2024-03-25 14:51 UTC, sanderr commented on docs/administrators/auth.rst
> +This section explain how to setup SSL. SSL is not strictly required for authentication but highly recommended.
```suggestion
This section explain how to setup SSL. SSL is not strictly required for authentication but it is highly recommended.
```

2024-03-25 14:51 UTC, sanderr commented on docs/administrators/auth.rst
> +Inmanta uses bearer tokens for authorizing users and services. These tokens should be kept private and are visible
```suggestion
Inmanta uses bearer tokens to authorize users and services. These tokens should be kept private and are visible
```

2024-03-25 14:51 UTC, sanderr commented on docs/administrators/auth.rst
> +below describe how to enable the built-in authentication provider and how to create the initial admin user.
```suggestion
below describe how to enable the built-in authentication provider and how to create the initial admin user.
Additional users can then be created via the API or through the web console.
```

2024-03-25 14:51 UTC, bartv approved these changes

2024-03-26 13:34 UTC, sanderr approved these changes

2024-03-26 13:36 UTC, inmantaci commented
Processing this pull request

2024-03-26 13:36 UTC, inmantaci commented
Failed to merge changes into iso6 due to merge conflict. Please open a pull request for these branches separately by cherry-picking the commit that was made on the branch master (git cherry-pick a1c1b683214f0cafa6b4f26d466b6934a0e6265f).

2024-03-26 13:36 UTC, inmantaci commented
Merged into branches master in a1c1b683214f0cafa6b4f26d466b6934a0e6265f

2024-03-26 13:36 UTC, inmantaci commented
Not closing this pull request due to previously commented issues for some of the destination branches. Please open a separate pull request for those branches by cherry-picking the relevant commit. You can safely close this pull request and delete the source branch.

2024-03-26 13:36 UTC, inmantaci commented
This branch was not deleted as it seems to still be in use.

2024-03-26 13:58 UTC, inmantaci commented
Processing #7446.

2024-03-27 07:05 UTC, closed without merging