Fix bug regarding incorrect rendering of literval values
inmanta/inmanta-core pull request #7456
Opened 2024-03-27 14:09 UTC by arnaudsjs

# Description

Fix bug that causes literal values to be rendered incorrectly in the OpenAPI documentation.

closes inmanta/lsm#1586

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2024-03-27 15:02 UTC, FloLey approved these changes

2024-03-27 17:11 UTC, sanderr requested changes

2024-03-27 17:11 UTC, sanderr approved these changes

2024-03-28 07:16 UTC, arnaudsjs commented on changelogs/unreleased/fix-openapi-doc-literal-values.yml
> +destination-branches: [master, iso7, iso6]
Right. I don't think we have these literal values on iso6.

2024-03-28 07:41 UTC, inmantaci commented
Processing this pull request

2024-03-28 07:41 UTC, inmantaci commented
Merged into branches master in 7c551699fed52b9a23d07133bd1b6df537fd4a17

2024-03-28 07:41 UTC, closed without merging

2024-03-28 08:03 UTC, inmantaci commented
Processing #7460.