issue/7325-release-tool-version-tag
inmanta/inmanta-core pull request #7489
Opened 2024-04-03 13:24 UTC by FloLey

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-04-04 12:22 UTC, FloLey commented
https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/gh/inmanta/inmanta-core/7491

2024-04-04 12:32 UTC, sanderr requested changes
Fix and test look good, just a minor note on the changelog entry.

2024-04-04 12:32 UTC, sanderr commented on changelogs/unreleased/7325-release-tool-version-tag.yml
> +description: Remove the version_tag from the metadata of the .cfg files.
I would make this a bit more descriptive to an end user
```suggestion
description: "Module release tool: do not write internal field `version_tag` to `setup.cfg`.
```

2024-04-04 13:11 UTC, Hugo-Inmanta approved these changes

2024-04-05 07:30 UTC, sanderr approved these changes

2024-04-05 07:32 UTC, inmantaci commented
Processing this pull request

2024-04-05 07:32 UTC, inmantaci commented
Merged into branches master in 1fd53edcfdf601df7bd92d2d1c21e3ba444fec52

2024-04-05 07:32 UTC, closed without merging

2024-04-05 07:54 UTC, inmantaci commented
Processing #7493.

2024-04-05 07:54 UTC, inmantaci commented
Processing #7492.