Improve compatibility page
inmanta/inmanta-core pull request #7490
Opened 2024-04-04 10:09 UTC by Hugo-Inmanta

# Description

closes https://github.com/inmanta/inmanta-core/issues/7428

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-04-04 11:28 UTC, Hugo-Inmanta commented
On hold until 08/04 for discussion about  `rename / restructure json component_requirements? Discuss on Slack`

2024-04-08 14:08 UTC, arnaudsjs requested changes

2024-04-08 14:08 UTC, arnaudsjs commented on docs/_templates/components_requirements.tmpl
> +when installing the orchestrator via rpm as is recommended in the :ref:`install-server` section.
```suggestion
when installing the orchestrator via RPM as is recommended in the :ref:`install-server` section.
```

2024-04-08 14:08 UTC, arnaudsjs commented on docs/_templates/components_requirements.tmpl
> +The following table shows the range of compatible versions for Inmanta python components.
I think we should make it clear that the production version is the starting point and from that we define version constraints on the versions of the components.
```suggestion
The following table shows the ranges of the Inmanta Python components, this product version is compatible with.
```

2024-04-09 05:41 UTC, arnaudsjs commented on docs/_templates/components_requirements.tmpl
> +These compatible versions are defined for the whole lifetime of this major version i.e.
Based on Sander his comment on Slack I think we need to change the following here: 

* I would change the sentence "These compatible versions are defined for the whole lifetime of this major version i.e. they are not pinned to a specific three-digit version." to "the lower bound of these version constraints will remain the same for the whole lifetime of this major version". The latter is just a lot more clear to me.
* We also need to mention explicitly that these version constraints will only result in compatible versions of they are used as input towards a dependency resolver like pip. The current explanation gives the impression that if your installed packages satisfy these constraints, they are compatible with each other. But that's not necessarily true.

2024-04-09 06:47 UTC, arnaudsjs approved these changes

2024-04-10 08:33 UTC, inmantaci commented
Processing this pull request

2024-04-10 08:33 UTC, inmantaci commented
Merged into branches master in 42b588ea7d4457fbc7dc0f76b6b86b936e366987

2024-04-10 08:33 UTC, closed without merging

2024-04-10 08:55 UTC, inmantaci commented
Processing #7507.

2024-04-10 08:55 UTC, inmantaci commented
Processing #7506.