Issue/add get current resource state
inmanta/inmanta-core pull request #7598
Opened 2024-05-06 14:26 UTC by arnaudsjs

# Description

Add the get_current_resource_state() method to the database layer. This method is required by https://github.com/inmanta/inmanta-lsm/pull/1718.

# Self Check:

- [ ] ~~Attached issue to pull request~~
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~
- [ ] ~~If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2024-05-06 14:43 UTC, wouterdb commented on src/inmanta/data/__init__.py
> +    async def get_current_resource_state(
this could use some documentation. 

I don't understand why a 'get_current` also gets a model version as an argument?

2024-05-07 06:34 UTC, arnaudsjs commented on src/inmanta/data/__init__.py
> +    async def get_current_resource_state(
That's a leftover from a previous implementation. I'll fix it.

2024-05-07 06:48 UTC, arnaudsjs commented on src/inmanta/data/__init__.py
> +    async def get_current_resource_state(
Given the review of my other PR, we should actually just remove the `model_version` argument.

2024-05-07 08:37 UTC, sanderr requested changes
I agree with the comment to drop the `model_version` parameter. Other than that two tiny comments.

2024-05-07 08:37 UTC, sanderr commented on src/inmanta/data/__init__.py
> +    async def get_status_for_v2(
Perhaps a more informative name would be `get_status_for_version` for the other method, and plain `get_status_for` / `get_status` for this one? As I understand it this one gets the current status of a resource, while the other gets the status for a specific version of a resource.

2024-05-07 08:37 UTC, sanderr commented on src/inmanta/data/__init__.py
> +    @classmethod
```suggestion
    @stable_api
    @classmethod
```

2024-05-07 08:55 UTC, sanderr approved these changes

2024-05-07 09:58 UTC, wouterdb commented on src/inmanta/data/__init__.py
> +    async def get_current_resource_state(cls, env: uuid.UUID, rid: ResourceIdStr) -> Optional[ResourceState]:
Do we need to also include the check on the hash or this that for another PR?

2024-05-07 10:52 UTC, wouterdb approved these changes

2024-05-07 11:43 UTC, inmantaci commented
Processing this pull request

2024-05-07 11:43 UTC, inmantaci commented
Merged into branches master in fa57043b1c0fb464a4d5c713da6626abf7d0ef61

2024-05-07 11:43 UTC, closed without merging

2024-05-07 12:06 UTC, inmantaci commented
Processing #7603.