Issue/issue/remove std config file usages iso6
inmanta/inmanta-core pull request #7638
Opened 2024-05-17 09:07 UTC by Hugo-Inmanta

# Description

iso6-specific PR for https://github.com/inmanta/inmanta-core/pull/7636

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

~~- [ ] Attached issue to pull request~~
- [x] Changelog entry
~~- [ ] Type annotations are present~~
~~- [ ] Code is clear and sufficiently documented~~
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
~~- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)~~
~~- [ ] Correct, in line with design~~
~~- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~
~~- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2024-05-17 09:31 UTC, arnaudsjs approved these changes

2024-05-17 13:49 UTC, sanderr commented on tests/test_app_cli.py
>  vm1=std::Host(name="non-existing-machine", os=std::linux)
This should probably go now

2024-05-17 14:17 UTC, Hugo-Inmanta commented on tests/test_app_cli.py
> +std::testing::NullResource(name="test", agentname="agent")
[Discussion](https://inmanta.slack.com/archives/CKRF0C8R3/p1715953214356089) about why this is here
> ... agentname="agent")

2024-05-21 09:45 UTC, arnaudsjs requested changes

2024-05-21 09:45 UTC, arnaudsjs commented on tests/test_app_cli.py
> +std::testing::NullResource(name="test", agentname="not_internal")
```suggestion
std::testing::NullResource(name="test", agentname="non_existing_agent")
```

2024-05-21 11:41 UTC, arnaudsjs approved these changes

2024-05-21 11:47 UTC, inmantaci commented
Merged into branches iso6 in 78c1a20444d6f81dfae74455a12b777eac5ac220

2024-05-21 11:47 UTC, closed without merging