Issue/fix test export
inmanta/inmanta-core pull request #7647
Opened 2024-05-21 09:26 UTC by Hugo-Inmanta

# Description

Follow-up to iso6 [PR](https://github.com/inmanta/inmanta-core/pull/7638).

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

~~- [ ] Attached issue to pull request~~
- [x] Changelog entry
~~- [ ] Type annotations are present~~
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
~~- [ ] Correct, in line with design~~
~~- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-05-21 09:29 UTC, Hugo-Inmanta commented
@arnaudsjs  Just to be sure, the last bullet point of the checklist: `If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)` is not relevant here right ?

2024-05-21 09:32 UTC, arnaudsjs requested changes

2024-05-21 09:32 UTC, arnaudsjs commented on tests/test_app_cli.py
> +std::testing::NullResource(name="test", agentname="not_internal")
This makes more clear what the intention is.
```suggestion
std::testing::NullResource(name="test", agentname="non_existing_agent")
```

2024-05-21 09:35 UTC, arnaudsjs approved these changes

2024-05-21 09:38 UTC, arnaudsjs commented
> @arnaudsjs Just to be sure, the last bullet point of the checklist: `If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)` is not relevant here right ?

Indeed. This is only relevant if the bug also exists on the stable repository. But that's not the case here.

2024-05-21 11:49 UTC, inmantaci commented
Processing this pull request

2024-05-21 11:49 UTC, inmantaci commented
Merged into branches master in 384b6a8a5ff4bd27ca7f9886005a288e3a98748d

2024-05-21 11:49 UTC, closed without merging

2024-05-21 12:25 UTC, inmantaci commented
Processing #7649.

2024-05-22 08:04 UTC, inmantaci commented
Processing #7649.