remove std resources from docs
inmanta/inmanta-core pull request #7735
Opened 2024-06-17 13:33 UTC by wouterdb

# Description

Remove references to std resources

closes #7563 
# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [ ] Type annotations are present
- [x] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-06-17 13:42 UTC, Hugo-Inmanta requested changes

2024-06-17 13:42 UTC, Hugo-Inmanta commented on docs/glossary.rst
> +        :inmanta:attribute:`memory_mb<vcenter::VirtualMachine.memory_mb>` attribute of the the :inmanta:entity:`vcenter::VirtualMachine`
```suggestion
        :inmanta:attribute:`memory_mb<vcenter::VirtualMachine.memory_mb>` attribute of the :inmanta:entity:`vcenter::VirtualMachine`
```

2024-06-17 13:45 UTC, Hugo-Inmanta approved these changes

2024-06-18 06:33 UTC, arnaudsjs approved these changes

2024-06-18 07:08 UTC, inmantaci commented
Merged into branches master in 7c788c1df7fabf27c53f3705db8e49119b303a4d

2024-06-18 07:08 UTC, closed without merging

2024-06-18 07:31 UTC, inmantaci commented
Processing #7739.