Switch to mypy baseline
inmanta/inmanta-core pull request #7788
Opened 2024-06-28 12:02 UTC by wouterdb

# Description

I've been using this for months now and it works really well. 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-06-28 12:04 UTC, jptrindade approved these changes

2024-06-28 12:06 UTC, hlloreda requested changes

2024-06-28 12:06 UTC, hlloreda commented on requirements.dev.txt
> +mypy-baseline
Shouldn't we set (freeze) the version?

2024-07-01 08:45 UTC, wouterdb commented on requirements.dev.txt
> +mypy-baseline
Perhaps I should just exclude iso6 from the change to keep it clean?

2024-07-01 08:46 UTC, arnaudsjs commented on requirements.dev.txt
> +mypy-baseline
I think that would be best

2024-07-01 09:33 UTC, hlloreda approved these changes

2024-07-01 09:45 UTC, arnaudsjs approved these changes

2024-07-01 09:49 UTC, Hugo-Inmanta approved these changes

2024-07-01 09:53 UTC, sanderr approved these changes
Nice!

2024-07-01 12:19 UTC, inmantaci commented
Processing this pull request

2024-07-01 12:19 UTC, inmantaci commented
Merged into branches master in 2697f5fa29a7319d882d48ca8d80455f86fba685

2024-07-01 12:19 UTC, closed without merging

2024-07-01 12:41 UTC, inmantaci commented
Processing #7793.