Remove outdated venvs
inmanta/inmanta-core pull request #7963
Opened 2024-08-08 14:14 UTC by hlloreda

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-08-16 07:36 UTC, wouterdb approved these changes

2024-08-20 08:09 UTC, sanderr requested changes

2024-08-20 08:09 UTC, sanderr commented on src/inmanta/agent/executor.py
> +        python_version = python_versions[0]
This relies on the same assumption as the line above, yet we don't assert it anywhere.

2024-08-20 13:39 UTC, sanderr approved these changes

2024-08-20 14:18 UTC, inmantaci commented
Processing this pull request

2024-08-20 14:18 UTC, inmantaci commented
Merged into branches master in c6c011ffec49d34c80492065c607463dc613b630

2024-08-20 14:18 UTC, closed without merging