Issue/8010 sacheduler agent side
inmanta/inmanta-core pull request #8049
Opened 2024-09-04 14:30 UTC by wouterdb

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-09-05 09:07 UTC, wouterdb commented on src/inmanta/agent/agent.py
> -        # store it outside the loop, but only load when required
refactored into code_manager class

2024-09-05 09:30 UTC, wouterdb commented on src/inmanta/deploy/work.py
> +    is_active: bool = True
I moved this here (instead of a set) for simplicity, I hope I didn't violate any delicate mechanism

2024-09-05 09:36 UTC, wouterdb commented on src/inmanta/util/async_lru.py
> +            fut.set_result(self.result)
This part is not like it was on https://github.com/python/cpython/issues/90780

it didn't work as proposed when the cache was hit before the awaitable was done.

I only half understand this code, but it seems to work

2024-09-05 10:23 UTC, wouterdb commented on mypy-baseline.txt
> +src/inmanta/util/async_lru.py:0: error: Function is missing a type annotation  [no-untyped-def]
I didn't manage, ...

2024-09-05 12:42 UTC, wouterdb commented on src/inmanta/agent/code_manager.py
> +    async def get_code_for_type(self, environment: uuid.UUID, version: int, resource_type: ResourceType) -> ResourceInstallSpec:
Now I look at this, failures are cached as well, that may not be the best idea...

2024-09-05 18:18 UTC, wouterdb commented on src/inmanta/deploy/state.py
> +        parsed_id = Id.parse_id(resource)
This comment I don't understand?

2024-09-06 08:32 UTC, hlloreda commented on src/inmanta/agent/code_manager.py
> +            return resource_install_spec
Maybe we could try to only cache this part?

2024-09-06 08:32 UTC, hlloreda commented on src/inmanta/deploy/state.py
> +        parsed_id = Id.parse_id(resource)
It looks like it was on outdated code

2024-09-06 09:17 UTC, arnaudsjs requested changes

2024-09-06 09:17 UTC, arnaudsjs commented on tests/agent_server/deploy/test_scheduler_e2e.py
> +    async def wait_for_resources(version, n):
Type annotations are missing.

2024-09-06 09:17 UTC, arnaudsjs commented on tests/agent_server/deploy/test_scheduler_e2e.py
> +            result = await client.get_version(env_id, version)
We need to use retry_limited here to prevent that we hang the test suite.

2024-09-06 09:17 UTC, arnaudsjs commented on tests/agent_server/deploy/test_scheduler_e2e.py
> +    result = await client.release_version(env_id, version1, False)
```suggestion
    result = await client.release_version(env_id, version1, push=False)
```

2024-09-06 09:17 UTC, arnaudsjs commented on tests/agent_server/deploy/test_scheduler_e2e.py
> +    await wait_for_resources(version1, 1)
```suggestion
    await wait_for_resources(version1, n=1)
```

2024-09-06 09:25 UTC, wouterdb commented on tests/util/test_async_lru.py
> +        await asyncio.sleep(0.01)
to make the second parallel  `"A"` hit the cache while the first is still in-flight

2024-09-06 09:28 UTC, wouterdb commented on src/inmanta/deploy/state.py
> +        self.types_per_agent[parsed_id.agent_name][parsed_id.entity_type] -= 1
not really, good idea

2024-09-06 09:30 UTC, wouterdb commented on src/inmanta/deploy/work.py
> +    def reset(self) -> None:
They are views on the requires_provides store in the state store, so they are cleaned there.

2024-09-06 12:12 UTC, arnaudsjs requested changes
See comment.

2024-09-06 14:07 UTC, wouterdb commented on src/inmanta/agent/agent_new.py
> +        )
Nope, depending on what you mean:
1. we don't support running the in_process with the scheduler
2. we actually run it, when using the MPExecutor, just not in the local process
3. in my test_scheduler_e2e, I actually do use it

2024-09-11 11:53 UTC, inmantaci commented
Processing this pull request

2024-09-11 11:53 UTC, inmantaci commented
Merged into branches master in c756a29d1293275409a907efa8ee9b17cf415a3a

2024-09-11 11:53 UTC, closed without merging