Introduce repair and redeploy timers to the new agent
inmanta/inmanta-core pull request #8126
Opened 2024-09-24 15:03 UTC by jptrindade

# Description

Copied over some logic from the old agent to introduce repair and redeploy timers

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-09-27 08:43 UTC, Hugo-Inmanta requested changes
Minor change on the test, lgtm otherwise :+1:

2024-09-27 08:43 UTC, Hugo-Inmanta commented on tests/agent_server/deploy/e2e/test_autostarted.py
> +        await asyncio.sleep(0.1)
The [`retry_limited`](https://github.com/inmanta/inmanta-core/blob/c4913c81e47e6dd01aaaa64a4372085d0dcf962b/tests/utils.py#L68) method can be used for this pattern.

2024-09-27 09:44 UTC, Hugo-Inmanta requested changes

2024-09-27 09:44 UTC, Hugo-Inmanta commented on tests/agent_server/deploy/e2e/test_autostarted.py
> +    def repaired() -> None:
```suggestion
    def repaired() -> bool:
```

2024-09-27 09:45 UTC, jptrindade commented on tests/agent_server/deploy/e2e/test_autostarted.py
> +    def repaired() -> None:
yup, my bad, rushed it a little bit

2024-09-30 11:50 UTC, sanderr requested changes
I'll start with a general concern: we have to make sure that these interval options can be changed and that we respond to it when they are. I have yet to consider how best to address this though.

2024-09-30 12:07 UTC, wouterdb commented on src/inmanta/agent/agent_new.py
> +        self._deploy_splay_value = random.randint(0, deploy_splay_time)
I think we plan to replace these timer mechanisms entirely, so yes

This implementation triggers all agents at once, so also yes

2024-09-30 12:36 UTC, sanderr requested changes
> I think we plan to replace these timer mechanisms entirely, so yes

@jptrindade considering Wouter's comment, I think we can leave the issue with the updating of the setting as is for now. But can you add a FIXME, noting that these settings are not currently updated (unlike the old agent) and that we should either fix it or rip this whole legacy timer out again?

2024-09-30 13:16 UTC, sanderr approved these changes

2024-09-30 13:32 UTC, inmantaci commented
Processing this pull request

2024-09-30 13:32 UTC, inmantaci commented
Merged into branches master in 80b6e63740608cc274bf73e99e3beac064c2820e

2024-09-30 13:32 UTC, closed without merging