First part of the move of the reporting to the scheduler
inmanta/inmanta-core pull request #8219
Opened 2024-10-16 12:55 UTC by wouterdb

# Description

First bit of #8189 

closes #8189 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-10-16 12:56 UTC, wouterdb commented on src/inmanta/agent/executor.py
> +class DeployResult:
This is the serializable form of the handler context

2024-10-16 13:03 UTC, wouterdb commented on tests/agent_server/deploy/test_scheduler_agent.py
> +        pass
todo: test state update consistency

2024-10-16 13:05 UTC, wouterdb commented on src/inmanta/deploy/tasks.py
>      async def execute(self, task_manager: "scheduler.TaskManager", agent: str) -> None:
TODO: make logging double to both DB and logger, as before

2024-10-16 13:12 UTC, bartv commented on src/inmanta/deploy/persistence.py
> +    Copyright 2024 Inmanta
What happened to all the newlines we normally have?

2024-10-22 15:39 UTC, wouterdb commented on src/inmanta/data/__init__.py
> -    changes: Optional[dict[m.ResourceIdStr, dict[str, object]]] = None
This was not correct

2024-10-22 15:39 UTC, wouterdb commented on src/inmanta/data/model.py
> +class ReleasedResourceState(StrEnum):
New mypy didn't like it, me neither

2024-10-24 07:18 UTC, arnaudsjs requested changes

2024-10-24 07:18 UTC, arnaudsjs commented on tests/deploy/test_scheduler_agent.py
> +        )
```suggestion
        return DeployResult(
            resource_details.rvid,
            action_id,
            status=result,
            messages=[],
            changes={},
            change=Change.nochange,
        )
```

2024-10-24 07:18 UTC, arnaudsjs commented on tests/deploy/test_scheduler_agent.py
> +        return DeployResult(resource_details.rvid, action_id, result, [], {}, Change.nochange)
```suggestion
        return DeployResult(resource_details.rvid, action_id, status=result, messages=[], changes={}, change=Change.nochange)
```

2024-10-24 07:18 UTC, arnaudsjs commented on tests/deploy/test_scheduler_agent.py
> +state_translation_table = {
This needs a docstring. What does it represent?

2024-10-24 07:18 UTC, arnaudsjs commented on tests/deploy/test_scheduler_agent.py
> +    def check_with_scheduler(self, scheduler: ResourceScheduler) -> None:
This method needs a docstring

2024-10-24 07:25 UTC, wouterdb commented on src/inmanta/deploy/persistence.py
> +            message = "multiple resources: " + message
nope, copy-paste, can't even happen anymore, will fix, thx.

2024-10-24 08:30 UTC, wouterdb commented on tests/deploy/e2e/test_autostarted.py
> -    assert result.result["model"]["result"] == "failed"
I stopped updating the state of the model, will be cleaned up in https://github.com/inmanta/inmanta-core/issues/8252

2024-10-24 08:39 UTC, arnaudsjs approved these changes

2024-10-24 09:15 UTC, Hugo-Inmanta requested changes

2024-10-24 09:15 UTC, Hugo-Inmanta commented on src/inmanta/agent/in_process_executor.py
> -        await self._report_resource_deploy_done(resource_details, ctx)
I think this obsolete method can be removed.

2024-10-24 14:27 UTC, Hugo-Inmanta approved these changes

2024-10-24 15:09 UTC, inmantaci commented
Processing this pull request

2024-10-24 15:09 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2024-10-24 19:19 UTC, inmantaci commented
Processing this pull request

2024-10-24 19:19 UTC, inmantaci commented
Merged into branches master in a9d6adc8e9cedfd0c59752411e4fddce1c66bd8a

2024-10-24 19:19 UTC, closed without merging