Issue/8184 remove agent 1
inmanta/inmanta-core pull request #8234
Opened 2024-10-21 07:54 UTC by wouterdb

# Description

Removed the agent.

(Which is very weird, after maintaining it for so long).

1. Most of this is reworking tests, some test have skips, to be investigated later

closes #8184 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-10-21 07:55 UTC, wouterdb commented on changelogs/unreleased/8184_remove_agent.yml
> +destination-branches: [master]
Final changelog entry to be added when the epic is done

2024-10-21 07:56 UTC, wouterdb commented on src/inmanta/server/agentmanager.py
> +        env: uuid.UUID,
Updated typing for convenience.

2024-10-21 07:56 UTC, wouterdb commented on src/inmanta/server/agentmanager.py
> +        assert not assert_no_start_scheduler
purely for tetsing

2024-10-21 08:01 UTC, bartv approved these changes
Looks good. What is the plan with the skipped tests?

2024-10-21 08:01 UTC, wouterdb commented on tests/conftest.py
>  import logging.config
All fixtures the agent_server subfolder are now here

2024-10-21 08:08 UTC, wouterdb commented
> Looks good. What is the plan with the skipped tests?

https://github.com/inmanta/inmanta-core/issues/8235

2024-10-21 11:57 UTC, arnaudsjs requested changes

2024-10-21 11:57 UTC, arnaudsjs commented on tests/conftest.py
> +    """Marker fixture, indicates we done expected scheduler autostart, any attempt to start the scheduler results in failure"""
```suggestion
    """Marker fixture, indicates we do expect scheduler autostart, any attempt to start the scheduler results in failure"""
```

2024-10-21 11:57 UTC, arnaudsjs commented on tests/deploy/e2e/test_code_loading.py
> +    # assert not os.path.exists(os.path.join(executor_manager._loader.mod_dir, "tests"))
What about this?

2024-10-22 08:13 UTC, wouterdb commented on tests/deploy/e2e/test_code_loading.py
> +    # assert not os.path.exists(os.path.join(executor_manager._loader.mod_dir, "tests"))
removed thx

2024-10-22 11:11 UTC, arnaudsjs approved these changes

2024-10-22 12:09 UTC, inmantaci commented
Processing this pull request

2024-10-22 12:09 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2024-10-22 12:25 UTC, inmantaci commented
Processing this pull request

2024-10-22 12:25 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2024-10-22 12:40 UTC, inmantaci commented
Processing this pull request

2024-10-22 12:40 UTC, inmantaci commented
Merged into branches master in 31c42204e6bd63475bf37cc4974ddc42c1b3f5b5

2024-10-22 12:40 UTC, closed without merging