refactor for reason field
inmanta/inmanta-core pull request #8275
Opened 2024-10-28 08:45 UTC by wouterdb

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-10-28 08:45 UTC, wouterdb commented on src/inmanta/deploy/work.py
> +    reason: str | None = None
Do I take this out of `__eq__` ?

2024-10-28 13:37 UTC, sanderr reviewed
The changes are not complete (e.g. bumping is missing) but I think that you are aware of that, given that this is a draft review of the concept rather than a full solution?

2024-10-29 13:35 UTC, hlloreda approved these changes

2024-10-29 16:16 UTC, sanderr requested changes

2024-10-29 16:16 UTC, sanderr commented on src/inmanta/deploy/scheduler.py
> +    async def deploy(self, reason: str, priority: TaskPriority = TaskPriority.USER_DEPLOY) -> None:
I'd prefer this as a kw-only arg but I'm not against it like this.

2024-10-30 12:29 UTC, sanderr approved these changes

2024-10-30 12:30 UTC, inmantaci commented
Processing this pull request

2024-10-30 12:30 UTC, inmantaci commented
Merged into branches master in 3d3a788b3fe0328356b6f82cc69a0984bcbb15c7

2024-10-30 12:30 UTC, closed without merging