Drop // syntax for comments
inmanta/inmanta-core pull request #8334
Opened 2024-11-07 16:17 UTC by jptrindade

# Description

Drop // syntax for comments

closes #6972 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-11-08 10:49 UTC, Hugo-Inmanta reviewed
I think we could add a small section about comments to the Inmanta language reference https://docs.inmanta.com/inmanta-service-orchestrator/7/language.html#language-reference

2024-11-08 10:49 UTC, Hugo-Inmanta commented on changelogs/unreleased/6972-drop-double-slash-comment-syntax.yml
> +    The // syntax for comments is no longer supported. Please use # for comments.
Could you double check that this renders nicely in the changelog page ?

2024-11-14 16:25 UTC, jptrindade commented
I added a section in the documentation, but still couldn't figure out how to see if the changelog renders correctly

2024-11-15 07:05 UTC, Hugo-Inmanta approved these changes

2024-11-15 10:16 UTC, inmantaci commented
Processing this pull request

2024-11-15 10:16 UTC, inmantaci commented
Pull request rejected by merge tool. This pull request has not been approved yet by some of the requested reviewers. Still awaiting approval from sanderr

2024-11-15 12:53 UTC, sanderr requested changes

2024-11-15 12:53 UTC, sanderr commented on tests/test_parser.py
> +    # // comments are no longer supported
This message refers to a change in this PR, not to anything related to the resulting test. I think it should go, because it's meaning is unclear.

2024-11-15 15:18 UTC, sanderr approved these changes

2024-11-15 15:33 UTC, inmantaci commented
Processing this pull request

2024-11-15 15:33 UTC, closed without merging