remove code reloading
inmanta/inmanta-core pull request #8375
Opened 2024-11-19 15:38 UTC by Hugo-Inmanta

# Description

* Short description here *

closes https://github.com/inmanta/inmanta-core/issues/8185

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
~~- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~
~~- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)~~

2024-11-26 07:44 UTC, Hugo-Inmanta commented on tests/test_loader.py
> +        import inmanta_plugins.inmanta_bad_unit_test  # NOQA
This was previously relying on the fact that the reloading would try importing, we have to explicitly call `import` now.

2024-11-26 10:12 UTC, arnaudsjs requested changes

2024-11-26 10:12 UTC, arnaudsjs commented on tests/test_loader.py
> +        assert "ModuleNotFoundError: No module named 'badimmport'" in caplog.text
We have to do `caplog.clear()` before the second import I guess?

2024-11-26 10:23 UTC, jptrindade approved these changes

2024-11-28 10:33 UTC, arnaudsjs approved these changes

2024-11-29 10:21 UTC, jptrindade approved these changes

2024-11-29 10:24 UTC, inmantaci commented
Processing this pull request

2024-11-29 10:24 UTC, inmantaci commented
Merged into branches master in de6ecd2aacec079dec7bf440b71d961508ce558a

2024-11-29 10:24 UTC, closed without merging