Issue/8303 document environment variables for config options
inmanta/inmanta-core pull request #8474
Opened 2024-12-13 15:24 UTC by Hugo-Inmanta

# Description

* Short description here *

closes  https://github.com/inmanta/inmanta-core/issues/8303

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-12-13 15:43 UTC, Hugo-Inmanta commented
Latest look: 
![image](https://github.com/user-attachments/assets/65a23ec1-5436-4bb3-a886-a3798781f044)

2024-12-13 15:48 UTC, Hugo-Inmanta commented on docs/reference/config.rst
> +about precedence rules, please visit the administrator documentation configuration :ref:`page<configuration_framework>`.
Some of it is redundant with the administrator documentation page, and I'm not sure how much value the example brings. Maybe only add the link to the administrator documentation page ?

2024-12-13 15:55 UTC, Hugo-Inmanta commented
@arnaudsjs I'm not sure about the relative pinning between core and inmanta-sphinx. Currently tests for [inmanta-sphinx](https://github.com/inmanta/inmanta-sphinx/pull/79) are failing because the code is not there present on core master.
And the tests here are failing because inmanta-sphinx 2.2.0 that contains required changed is not released yet.

2024-12-16 07:21 UTC, arnaudsjs requested changes

2024-12-16 07:21 UTC, arnaudsjs commented on tests/test_config.py
> +        - via environment variable
This doesn't mentioned to dot files.

2024-12-16 07:24 UTC, arnaudsjs commented
> @arnaudsjs I'm not sure about the relative pinning between core and inmanta-sphinx. Currently tests for [inmanta-sphinx](https://github.com/inmanta/inmanta-sphinx/pull/79) are failing because the code is not there present on core master. And the tests here are failing because inmanta-sphinx 2.2.0 that contains required changed is not released yet.

Ideally you do this via three PRs:
* One PR on inmanta-core that adds the `get_environment_variable()` method.
* Then the PR on inmanta-sphinx.
* Finally the PR on inmanta-core that updates the documentation. (This PR can bump the version of inmanta-sphinx, but it might be that dependabot is quicker.)

2024-12-17 10:47 UTC, arnaudsjs approved these changes

2024-12-17 10:58 UTC, inmantaci commented
Processing this pull request

2024-12-17 10:58 UTC, inmantaci commented
Merged into branches master in f6e4df0e1ea2ee31e6592337128d5ba8e883bc4b

2024-12-17 10:58 UTC, closed without merging

2024-12-17 11:20 UTC, inmantaci commented
Processing #8486.