Logging force tty when generating default config
inmanta/inmanta-core pull request #8540
Opened 2024-12-31 09:50 UTC by jptrindade

# Description

Added the option to `force_tty` on `_get_multiline_formatter_config` so that we output the same config when printing on the console or writing the config to a file

closes #8484 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Type annotations are present
- [x] Code is clear and sufficiently documented
- [x] No (preventable) type errors (check using make mypy or make mypy-diff)
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )
- [ ] If this PR fixes a race condition in the test suite, also push the fix to the relevant stable branche(s) (see [test-fixes](https://internal.inmanta.com/development/core/tasks/build-master.html#test-fixes) for more info)

2024-12-31 09:58 UTC, jptrindade commented
@sanderr I added you as a reviewer just in case you were curious about the test case.

2025-01-02 07:31 UTC, arnaudsjs requested changes

2025-01-02 07:31 UTC, arnaudsjs commented on src/inmanta/app.py
> +            del os.environ[const.ENVIRON_FORCE_TTY]
* The except clause is redundant.
* If `original_force_tty` is set to an empty string, we will overwrite the value with "yes". This makes the comment "Revert this env var back to its original state" invalid.

```suggestion
    # Force TTY so that this command outputs the same config when piping to a file
    original_force_tty = os.environ.get(const.ENVIRON_FORCE_TTY, None)
    if original_force_tty is None:
        os.environ[const.ENVIRON_FORCE_TTY] = "yes"
    try:
        component_config.apply_options(options, options.cmd, context)
    finally:
        # Revert this env var back to its original state
        if original_force_tty is None:
            del os.environ[const.ENVIRON_FORCE_TTY]
```

2025-01-02 07:31 UTC, arnaudsjs commented on src/inmanta/app.py
> +    # Force TTY so that this command outputs the same config when piping to a file
The call to `start_loggers_for_extensions()` also extends the logging config, so we need to make sure that the environment variable is also set for that call. Why not set is for this entire method?

2025-01-02 07:31 UTC, arnaudsjs commented on tests/test_logging.py
> +        process = await subprocess.create_subprocess_exec(*args, stdout=subprocess.PIPE)
```suggestion
        # This is the same as piping to a file
        assert "ENVIRON_FORCE_TTY" not in os.environ
        process = await subprocess.create_subprocess_exec(*args, stdout=subprocess.PIPE)
```

2025-01-02 07:31 UTC, arnaudsjs commented on tests/test_logging.py
> +        await process.wait()
As the documentation mentions, `process.wait()` can deadlock when `subprocess.PIPE` is used. I don't really see why this call is required, given that we already call into `process.communicate()`.

2025-01-02 07:31 UTC, arnaudsjs commented on tests/test_logging.py
> +            *args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env={ENVIRON_FORCE_TTY: "yes"}
```suggestion
        process = await subprocess.create_subprocess_exec(
            *args, stdout=subprocess.PIPE, env={ENVIRON_FORCE_TTY: "yes"}
```

2025-01-02 09:52 UTC, jptrindade commented on src/inmanta/app.py
> +    # Force TTY so that this command outputs the same config when piping to a file
I'm not sure it uses the `_is_on_tty` which, I believe, is the only real relevant reason why we set the environment variable. I set the environment variable to the whole method anyway, just to avoid some errors in the future if we end up using the `_is_on_tty` in other parts of this code

2025-01-02 09:54 UTC, arnaudsjs commented on src/inmanta/app.py
> +    # Force TTY so that this command outputs the same config when piping to a file
I know. My main concern here was to make it future proof.

2025-01-02 10:04 UTC, arnaudsjs approved these changes

2025-01-02 10:22 UTC, inmantaci commented
Pull request rejected by merge tool. This pull request has not been approved yet by some of the requested reviewers. Still awaiting approval from sanderr

2025-01-04 08:30 UTC, wouterdb approved these changes

2025-01-06 08:51 UTC, inmantaci commented
Pull request rejected by merge tool. Pull request is not mergeable. Please check for merge conflicts before re-adding the merge-tool-ready label.

2025-01-06 09:35 UTC, inmantaci commented
Processing this pull request

2025-01-06 09:35 UTC, inmantaci commented
Merged into branches master in 941382088c525a56c0a415a93330f53058a4b000

2025-01-06 09:35 UTC, closed without merging